import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  poweredByHeader: false,
  /**
   * `next dev` otherwise writes its own `apps/web/AGENTS.md` and `CLAUDE.md` on
   * every start, and re-creates them when they are deleted. This repo already
   * carries hand-maintained agent instructions at the root, which CLAUDE.md
   * requires be kept in sync with AGENTS.md; a second, machine-authored pair one
   * directory down is a governance file nobody reviewed and a permanent dirty
   * working tree.
   */
  agentRules: false,
  /**
   * Typed routes are off, deliberately.
   *
   * They are generated by `next build` into `.next/types`, but this repo's
   * verify order runs `type-check` before `build`, and CI runs it on a fresh
   * checkout with no `.next` at all. So the gate passes locally, disappears in
   * CI, and fails whenever the two disagree.
   *
   * The second reason is structural: the command palette is registry-driven and
   * pushes hrefs that are built at runtime (`/patients/<id>`), which typed
   * routes cannot express without a cast at every call site. Routes are instead
   * declared once in `src/components/shell/navigation.ts`, and the route
   * skeletons are the compile-time proof that each one exists.
   */
  typedRoutes: false,
};

export default nextConfig;
