-- The EMR data model: 47 tables, 58 enums.
--
-- Generated by `prisma migrate diff` against the applied 0000000000000_init
-- state, so it reproduces prisma/schema.prisma exactly. Two things were added
-- by hand and nothing generated was removed:
--   1. this comment;
--   2. the precondition guard immediately below.
--
-- Precondition: AuditEvent must be empty. This migration converts its `id`
-- from TEXT to UUID and adds NOT NULL `tenantId`, `seq`, `prevHash` and `hash`
-- columns that have no correct backfill value - a fabricated tenant or a
-- fabricated hash would silently forge the audit chain. Openrunic has never
-- been released with a populated AuditEvent table, so this holds everywhere it
-- can legitimately run. If it ever does not, the operator gets a clear failure
-- instead of a corrupted chain: export the rows, then run a bespoke backfill.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "AuditEvent") THEN
    RAISE EXCEPTION 'Migration 20260813000000_emr_data_model requires an empty AuditEvent table. Export the existing rows and backfill tenantId/seq/prevHash/hash before applying.';
  END IF;
END
$$;

-- CreateEnum
CREATE TYPE "OrganisationMode" AS ENUM ('SAAS', 'SELF_HOST');

-- CreateEnum
CREATE TYPE "OrganisationStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED');

-- CreateEnum
CREATE TYPE "SensitivityClass" AS ENUM ('NORMAL', 'RESTRICTED', 'VERY_RESTRICTED');

-- CreateEnum
CREATE TYPE "AdministrativeGender" AS ENUM ('FEMALE', 'MALE', 'OTHER', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "IdentifierUse" AS ENUM ('USUAL', 'OFFICIAL', 'TEMP', 'SECONDARY', 'OLD');

-- CreateEnum
CREATE TYPE "CoverageRank" AS ENUM ('PRIMARY', 'SECONDARY', 'TERTIARY');

-- CreateEnum
CREATE TYPE "CoverageStatus" AS ENUM ('DRAFT', 'ACTIVE', 'CANCELLED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('PROPOSED', 'PENDING', 'BOOKED', 'ARRIVED', 'CHECKED_IN', 'ROOMED', 'IN_PROGRESS', 'CHECKED_OUT', 'FULFILLED', 'CANCELLED', 'NOSHOW', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "AppointmentCreatedVia" AS ENUM ('STAFF', 'PORTAL', 'WAITLIST', 'RECALL', 'IMPORT');

-- CreateEnum
CREATE TYPE "EncounterClass" AS ENUM ('AMBULATORY', 'VIRTUAL', 'HOME', 'FIELD', 'EMERGENCY');

-- CreateEnum
CREATE TYPE "EncounterStatus" AS ENUM ('PLANNED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "NoteState" AS ENUM ('DRAFT', 'AI_DRAFT_REVIEW', 'UNSIGNED', 'SIGNED', 'AMENDED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "ConditionCategory" AS ENUM ('PROBLEM_LIST_ITEM', 'ENCOUNTER_DIAGNOSIS', 'SURGERY', 'DENTAL');

-- CreateEnum
CREATE TYPE "ConditionClinicalStatus" AS ENUM ('ACTIVE', 'RECURRENCE', 'RELAPSE', 'INACTIVE', 'REMISSION', 'RESOLVED');

-- CreateEnum
CREATE TYPE "ConditionVerificationStatus" AS ENUM ('UNCONFIRMED', 'PROVISIONAL', 'DIFFERENTIAL', 'CONFIRMED', 'REFUTED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "MedicationStatementStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'ENTERED_IN_ERROR', 'INTENDED', 'STOPPED', 'ON_HOLD', 'NOT_TAKEN', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "MedicationSource" AS ENUM ('REPORTED', 'PRESCRIBED', 'RECONCILED', 'IMPORTED');

-- CreateEnum
CREATE TYPE "MedicationRequestStatus" AS ENUM ('DRAFT', 'PENDED', 'SIGNED', 'TRANSMITTED', 'ACTIVE', 'ON_HOLD', 'CANCELLED', 'COMPLETED', 'STOPPED', 'ERROR');

-- CreateEnum
CREATE TYPE "MedicationRequestIntent" AS ENUM ('PROPOSAL', 'PLAN', 'ORDER', 'ORIGINAL_ORDER', 'REFILL');

-- CreateEnum
CREATE TYPE "AllergyType" AS ENUM ('ALLERGY', 'INTOLERANCE');

-- CreateEnum
CREATE TYPE "AllergyCategory" AS ENUM ('FOOD', 'MEDICATION', 'ENVIRONMENT', 'BIOLOGIC');

-- CreateEnum
CREATE TYPE "AllergyCriticality" AS ENUM ('LOW', 'HIGH', 'UNABLE_TO_ASSESS');

-- CreateEnum
CREATE TYPE "AllergyClinicalStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'RESOLVED');

-- CreateEnum
CREATE TYPE "ReactionSeverity" AS ENUM ('MILD', 'MODERATE', 'SEVERE');

-- CreateEnum
CREATE TYPE "ImmunizationStatus" AS ENUM ('COMPLETED', 'NOT_DONE', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "ObservationCategory" AS ENUM ('VITAL_SIGNS', 'LABORATORY', 'IMAGING', 'SOCIAL_HISTORY', 'SDOH', 'SURVEY', 'EXAM', 'PROCEDURE', 'THERAPY', 'ACTIVITY');

-- CreateEnum
CREATE TYPE "ObservationStatus" AS ENUM ('REGISTERED', 'PRELIMINARY', 'FINAL', 'AMENDED', 'CORRECTED', 'CANCELLED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "AbnormalFlag" AS ENUM ('NORMAL', 'ABNORMAL', 'CRITICAL');

-- CreateEnum
CREATE TYPE "OrderPriority" AS ENUM ('ROUTINE', 'URGENT', 'ASAP', 'STAT');

-- CreateEnum
CREATE TYPE "ServiceRequestCategory" AS ENUM ('LAB', 'IMAGING', 'PROCEDURE', 'REFERRAL', 'THERAPY');

-- CreateEnum
CREATE TYPE "ServiceRequestStatus" AS ENUM ('DRAFT', 'PENDED', 'SIGNED', 'TRANSMITTED', 'IN_PROGRESS', 'RESULTED', 'COMPLETED', 'CANCELLED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "ServiceRequestIntent" AS ENUM ('PROPOSAL', 'PLAN', 'ORDER', 'ORIGINAL_ORDER', 'REFLEX_ORDER');

-- CreateEnum
CREATE TYPE "SpecimenStatus" AS ENUM ('AVAILABLE', 'UNAVAILABLE', 'UNSATISFACTORY', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "DiagnosticReportStatus" AS ENUM ('REGISTERED', 'PARTIAL', 'PRELIMINARY', 'FINAL', 'AMENDED', 'CORRECTED', 'APPENDED', 'CANCELLED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "DocumentSource" AS ENUM ('UPLOAD', 'SCAN', 'FAX', 'GENERATED', 'PORTAL', 'INTERFACE');

-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('INBOX', 'FILED', 'SUPERSEDED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "TaskType" AS ENUM ('RESULT', 'MESSAGE', 'REFILL', 'COSIGN', 'DOCUMENT', 'FAX', 'PRIOR_AUTH', 'CLAIM_EXCEPTION', 'GENERAL');

-- CreateEnum
CREATE TYPE "TaskStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'DONE', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "TaskPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');

-- CreateEnum
CREATE TYPE "TaskAssigneeType" AS ENUM ('USER', 'TEAM');

-- CreateEnum
CREATE TYPE "TaskSlaState" AS ENUM ('OK', 'AGING', 'BREACH');

-- CreateEnum
CREATE TYPE "ThreadKind" AS ENUM ('PATIENT', 'STAFF', 'CARE_TEAM');

-- CreateEnum
CREATE TYPE "MessageSenderType" AS ENUM ('USER', 'PATIENT', 'RELATED_PERSON', 'SYSTEM');

-- CreateEnum
CREATE TYPE "ChargeItemStatus" AS ENUM ('OPEN', 'BILLED', 'VOIDED');

-- CreateEnum
CREATE TYPE "ClaimStatus" AS ENUM ('DRAFT', 'SCRUBBED', 'SUBMITTED', 'ACKNOWLEDGED', 'REJECTED', 'DENIED', 'PAID', 'PARTIAL', 'REBILLED', 'VOID');

-- CreateEnum
CREATE TYPE "ClaimFrequency" AS ENUM ('ORIGINAL', 'REPLACEMENT', 'VOID');

-- CreateEnum
CREATE TYPE "PaymentSource" AS ENUM ('PATIENT', 'PAYER_ERA', 'ADAPTER', 'ADJUSTMENT');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('CASH', 'CHECK', 'CARD', 'ACH', 'EFT', 'OTHER');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'POSTED', 'FAILED', 'REFUNDED', 'VOIDED');

-- CreateEnum
CREATE TYPE "RemittanceStatus" AS ENUM ('RECEIVED', 'PARSED', 'POSTED', 'EXCEPTIONS');

-- CreateEnum
CREATE TYPE "StatementStatus" AS ENUM ('DRAFT', 'GENERATED', 'SENT', 'PAID', 'VOID');

-- CreateEnum
CREATE TYPE "StatementDelivery" AS ENUM ('PRINT', 'EMAIL', 'SMS', 'PORTAL');

-- CreateEnum
CREATE TYPE "FormStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'RETIRED');

-- CreateEnum
CREATE TYPE "FormBinding" AS ENUM ('PATIENT', 'ENCOUNTER', 'PORTAL', 'REFERRAL');

-- CreateEnum
CREATE TYPE "FormSubmissionStatus" AS ENUM ('IN_PROGRESS', 'COMPLETED', 'SIGNED', 'AMENDED', 'ENTERED_IN_ERROR');

-- CreateEnum
CREATE TYPE "FormCompletedByType" AS ENUM ('USER', 'PATIENT', 'RELATED_PERSON', 'SYSTEM');

-- CreateEnum
CREATE TYPE "ConsentStatus" AS ENUM ('PROPOSED', 'ACTIVE', 'REJECTED', 'REVOKED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "ConsentScope" AS ENUM ('TREATMENT', 'PORTAL_ACCESS', 'INFORMATION_SHARING', 'RESEARCH', 'COMMUNICATION', 'FINANCIAL');

-- AlterTable
ALTER TABLE "AuditEvent" DROP CONSTRAINT "AuditEvent_pkey",
ADD COLUMN     "actorDisplay" TEXT,
ADD COLUMN     "breakglass" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "encounterId" UUID,
ADD COLUMN     "facilityId" UUID,
ADD COLUMN     "hash" TEXT NOT NULL,
ADD COLUMN     "outcome" TEXT NOT NULL DEFAULT 'success',
ADD COLUMN     "patientId" UUID,
ADD COLUMN     "prevHash" TEXT NOT NULL,
ADD COLUMN     "purposeOfUse" TEXT,
ADD COLUMN     "seq" BIGINT NOT NULL,
ADD COLUMN     "sourceIp" TEXT,
ADD COLUMN     "tenantId" UUID NOT NULL,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "userAgent" TEXT,
DROP COLUMN "id",
ADD COLUMN     "id" UUID NOT NULL,
ADD CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id");

-- CreateTable
CREATE TABLE "Organisation" (
    "id" UUID NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "mode" "OrganisationMode" NOT NULL DEFAULT 'SELF_HOST',
    "status" "OrganisationStatus" NOT NULL DEFAULT 'ACTIVE',
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "flags" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Organisation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Facility" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "npi" TEXT,
    "posCode" TEXT,
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "addressLine1" TEXT,
    "addressLine2" TEXT,
    "city" TEXT,
    "state" TEXT,
    "postalCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'US',
    "phone" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Facility_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "givenName" TEXT NOT NULL,
    "familyName" TEXT NOT NULL,
    "credential" TEXT,
    "npi" TEXT,
    "dea" TEXT,
    "taxonomyCode" TEXT,
    "isProvider" BOOLEAN NOT NULL DEFAULT false,
    "locale" TEXT NOT NULL DEFAULT 'en-US',
    "status" "UserStatus" NOT NULL DEFAULT 'INVITED',
    "lastLoginAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserFacility" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "facilityId" UUID NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserFacility_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Role" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isSystem" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Permission" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Permission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RolePermission" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "roleId" UUID NOT NULL,
    "permissionId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoleAssignment" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "roleId" UUID NOT NULL,
    "facilityId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RoleAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Patient" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "mrn" TEXT NOT NULL,
    "primaryFacilityId" UUID,
    "givenName" TEXT NOT NULL,
    "middleName" TEXT,
    "familyName" TEXT NOT NULL,
    "prefix" TEXT,
    "suffix" TEXT,
    "preferredName" TEXT,
    "birthDate" DATE NOT NULL,
    "deceasedAt" TIMESTAMP(3),
    "sexAtBirth" "AdministrativeGender" NOT NULL DEFAULT 'UNKNOWN',
    "genderIdentityCode" TEXT,
    "pronouns" TEXT,
    "raceCodes" TEXT[],
    "ethnicityCodes" TEXT[],
    "languageCode" TEXT NOT NULL DEFAULT 'en',
    "maritalStatusCode" TEXT,
    "email" TEXT,
    "phoneMobile" TEXT,
    "phoneHome" TEXT,
    "addressLine1" TEXT,
    "addressLine2" TEXT,
    "city" TEXT,
    "state" TEXT,
    "postalCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'US',
    "sensitivityClass" "SensitivityClass" NOT NULL DEFAULT 'NORMAL',
    "portalEnabled" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Patient_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PatientIdentifier" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "use" "IdentifierUse" NOT NULL DEFAULT 'SECONDARY',
    "system" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "typeCode" TEXT,
    "assigner" TEXT,
    "periodStart" TIMESTAMP(3),
    "periodEnd" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PatientIdentifier_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RelatedPerson" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "relationshipCode" TEXT NOT NULL,
    "relationshipText" TEXT,
    "givenName" TEXT NOT NULL,
    "familyName" TEXT NOT NULL,
    "phone" TEXT,
    "email" TEXT,
    "addressLine1" TEXT,
    "city" TEXT,
    "state" TEXT,
    "postalCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'US',
    "isGuardian" BOOLEAN NOT NULL DEFAULT false,
    "isEmergencyContact" BOOLEAN NOT NULL DEFAULT false,
    "isPortalProxy" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RelatedPerson_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payer" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "x12PayerId" TEXT,
    "claimFilingCode" TEXT,
    "eligibilityPayerId" TEXT,
    "addressLine1" TEXT,
    "city" TEXT,
    "state" TEXT,
    "postalCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'US',
    "phone" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Coverage" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "payerId" UUID NOT NULL,
    "rank" "CoverageRank" NOT NULL DEFAULT 'PRIMARY',
    "status" "CoverageStatus" NOT NULL DEFAULT 'ACTIVE',
    "memberId" TEXT NOT NULL,
    "groupNumber" TEXT,
    "planName" TEXT,
    "subscriberRelationshipCode" TEXT NOT NULL DEFAULT 'self',
    "subscriberGivenName" TEXT,
    "subscriberFamilyName" TEXT,
    "subscriberBirthDate" DATE,
    "effectiveFrom" DATE,
    "effectiveTo" DATE,
    "copayCents" INTEGER,
    "deductibleCents" INTEGER,
    "acceptAssignment" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Coverage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Document" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID,
    "encounterId" UUID,
    "category" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "byteSize" INTEGER NOT NULL,
    "source" "DocumentSource" NOT NULL DEFAULT 'UPLOAD',
    "status" "DocumentStatus" NOT NULL DEFAULT 'INBOX',
    "sensitivityClass" "SensitivityClass" NOT NULL DEFAULT 'NORMAL',
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "filedAt" TIMESTAMP(3),
    "filedById" UUID,
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Appointment" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "facilityId" UUID NOT NULL,
    "patientId" UUID,
    "providerId" UUID NOT NULL,
    "typeCode" TEXT NOT NULL,
    "typeDisplay" TEXT NOT NULL,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'BOOKED',
    "start" TIMESTAMP(3) NOT NULL,
    "end" TIMESTAMP(3) NOT NULL,
    "durationMinutes" INTEGER NOT NULL,
    "room" TEXT,
    "reasonText" TEXT,
    "recurrenceGroupId" UUID,
    "recurrenceRule" JSONB,
    "createdVia" "AppointmentCreatedVia" NOT NULL DEFAULT 'STAFF',
    "cancelReason" TEXT,
    "checkedInAt" TIMESTAMP(3),
    "createdById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AppointmentStatusHistory" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "appointmentId" UUID NOT NULL,
    "status" "AppointmentStatus" NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "byUserId" UUID,
    "room" TEXT,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AppointmentStatusHistory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Encounter" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "facilityId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "providerId" UUID NOT NULL,
    "appointmentId" UUID,
    "class" "EncounterClass" NOT NULL DEFAULT 'AMBULATORY',
    "status" "EncounterStatus" NOT NULL DEFAULT 'PLANNED',
    "reasonCode" TEXT,
    "reasonText" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "endedAt" TIMESTAMP(3),
    "signedAt" TIMESTAMP(3),
    "signedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Encounter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClinicalNote" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID NOT NULL,
    "authorId" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "blocks" JSONB NOT NULL DEFAULT '[]',
    "state" "NoteState" NOT NULL DEFAULT 'DRAFT',
    "cosignerId" UUID,
    "cosignedAt" TIMESTAMP(3),
    "signedAt" TIMESTAMP(3),
    "signedById" UUID,
    "lockedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ClinicalNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NoteAddendum" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "noteId" UUID NOT NULL,
    "authorId" UUID NOT NULL,
    "blocks" JSONB NOT NULL DEFAULT '[]',
    "reason" TEXT,
    "signedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NoteAddendum_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Condition" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "category" "ConditionCategory" NOT NULL DEFAULT 'PROBLEM_LIST_ITEM',
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL DEFAULT 'http://hl7.org/fhir/sid/icd-10-cm',
    "display" TEXT NOT NULL,
    "snomedCode" TEXT,
    "clinicalStatus" "ConditionClinicalStatus" NOT NULL DEFAULT 'ACTIVE',
    "verificationStatus" "ConditionVerificationStatus" NOT NULL DEFAULT 'CONFIRMED',
    "onsetDate" DATE,
    "abatementDate" DATE,
    "severityCode" TEXT,
    "bodySiteCode" TEXT,
    "note" TEXT,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "recordedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Condition_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MedicationStatement" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "rxnormCode" TEXT,
    "display" TEXT NOT NULL,
    "sigText" TEXT,
    "status" "MedicationStatementStatus" NOT NULL DEFAULT 'ACTIVE',
    "source" "MedicationSource" NOT NULL DEFAULT 'REPORTED',
    "effectiveStart" DATE,
    "effectiveEnd" DATE,
    "reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MedicationStatement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MedicationRequest" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "prescriberId" UUID NOT NULL,
    "rxnormCode" TEXT,
    "ndcCode" TEXT,
    "display" TEXT NOT NULL,
    "sig" JSONB NOT NULL DEFAULT '{}',
    "sigText" TEXT NOT NULL,
    "quantity" DECIMAL(12,3) NOT NULL,
    "quantityUnit" TEXT NOT NULL,
    "refills" INTEGER NOT NULL DEFAULT 0,
    "daysSupply" INTEGER,
    "dispenseAsWritten" BOOLEAN NOT NULL DEFAULT false,
    "controlledSchedule" TEXT,
    "pharmacyName" TEXT,
    "pharmacyNcpdpId" TEXT,
    "status" "MedicationRequestStatus" NOT NULL DEFAULT 'DRAFT',
    "intent" "MedicationRequestIntent" NOT NULL DEFAULT 'ORDER',
    "erxRef" TEXT,
    "writtenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transmittedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MedicationRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AllergyIntolerance" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "type" "AllergyType" NOT NULL DEFAULT 'ALLERGY',
    "category" "AllergyCategory" NOT NULL DEFAULT 'MEDICATION',
    "criticality" "AllergyCriticality" NOT NULL DEFAULT 'UNABLE_TO_ASSESS',
    "clinicalStatus" "AllergyClinicalStatus" NOT NULL DEFAULT 'ACTIVE',
    "substanceCode" TEXT,
    "substanceCodeSystem" TEXT,
    "substanceDisplay" TEXT NOT NULL,
    "reactionCodes" TEXT[],
    "reactionText" TEXT,
    "severity" "ReactionSeverity",
    "onsetDate" DATE,
    "note" TEXT,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "recordedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AllergyIntolerance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Immunization" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "status" "ImmunizationStatus" NOT NULL DEFAULT 'COMPLETED',
    "cvxCode" TEXT NOT NULL,
    "mvxCode" TEXT,
    "ndcCode" TEXT,
    "display" TEXT NOT NULL,
    "lotNumber" TEXT,
    "expirationDate" DATE,
    "siteCode" TEXT,
    "routeCode" TEXT,
    "doseQuantity" DECIMAL(8,3),
    "doseUnit" TEXT,
    "administeredAt" TIMESTAMP(3) NOT NULL,
    "administeredById" UUID,
    "visDate" DATE,
    "refusalReasonCode" TEXT,
    "reportedToRegistryAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Immunization_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Observation" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "category" "ObservationCategory" NOT NULL DEFAULT 'VITAL_SIGNS',
    "status" "ObservationStatus" NOT NULL DEFAULT 'FINAL',
    "loincCode" TEXT,
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL DEFAULT 'http://loinc.org',
    "display" TEXT NOT NULL,
    "valueNumber" DECIMAL(18,6),
    "valueText" TEXT,
    "valueCode" TEXT,
    "valueBoolean" BOOLEAN,
    "unit" TEXT,
    "referenceLow" DECIMAL(18,6),
    "referenceHigh" DECIMAL(18,6),
    "interpretationCode" TEXT,
    "bodySiteCode" TEXT,
    "effectiveAt" TIMESTAMP(3) NOT NULL,
    "issuedAt" TIMESTAMP(3),
    "performerId" UUID,
    "formSubmissionId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Observation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ServiceRequest" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "orderedById" UUID NOT NULL,
    "category" "ServiceRequestCategory" NOT NULL DEFAULT 'LAB',
    "status" "ServiceRequestStatus" NOT NULL DEFAULT 'DRAFT',
    "intent" "ServiceRequestIntent" NOT NULL DEFAULT 'ORDER',
    "priority" "OrderPriority" NOT NULL DEFAULT 'ROUTINE',
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL,
    "display" TEXT NOT NULL,
    "specimenTypeCode" TEXT,
    "reasonCodes" TEXT[],
    "aoeAnswers" JSONB,
    "note" TEXT,
    "requisitionNumber" TEXT,
    "performingLabName" TEXT,
    "labRef" TEXT,
    "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "scheduledFor" TIMESTAMP(3),
    "transmittedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ServiceRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Specimen" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "serviceRequestId" UUID,
    "status" "SpecimenStatus" NOT NULL DEFAULT 'AVAILABLE',
    "accessionNumber" TEXT,
    "typeCode" TEXT NOT NULL,
    "typeDisplay" TEXT NOT NULL,
    "collectionMethodCode" TEXT,
    "bodySiteCode" TEXT,
    "collectedAt" TIMESTAMP(3),
    "collectedById" UUID,
    "receivedAt" TIMESTAMP(3),
    "containerType" TEXT,
    "volumeValue" DECIMAL(10,3),
    "volumeUnit" TEXT,
    "rejectionReason" TEXT,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Specimen_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DiagnosticReport" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "serviceRequestId" UUID,
    "specimenId" UUID,
    "status" "DiagnosticReportStatus" NOT NULL DEFAULT 'FINAL',
    "category" "ServiceRequestCategory" NOT NULL DEFAULT 'LAB',
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL DEFAULT 'http://loinc.org',
    "display" TEXT NOT NULL,
    "performingLabName" TEXT,
    "abnormalFlag" "AbnormalFlag" NOT NULL DEFAULT 'NORMAL',
    "narrative" TEXT,
    "rawStorageKey" TEXT,
    "effectiveAt" TIMESTAMP(3),
    "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedById" UUID,
    "reviewedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DiagnosticReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ResultObservation" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "diagnosticReportId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "status" "ObservationStatus" NOT NULL DEFAULT 'FINAL',
    "sequence" INTEGER NOT NULL,
    "loincCode" TEXT,
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL DEFAULT 'http://loinc.org',
    "display" TEXT NOT NULL,
    "valueNumber" DECIMAL(18,6),
    "valueText" TEXT,
    "valueCode" TEXT,
    "unit" TEXT,
    "referenceLow" DECIMAL(18,6),
    "referenceHigh" DECIMAL(18,6),
    "referenceRangeText" TEXT,
    "interpretationCode" TEXT,
    "abnormalFlag" "AbnormalFlag" NOT NULL DEFAULT 'NORMAL',
    "effectiveAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ResultObservation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Task" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "type" "TaskType" NOT NULL DEFAULT 'GENERAL',
    "status" "TaskStatus" NOT NULL DEFAULT 'OPEN',
    "priority" "TaskPriority" NOT NULL DEFAULT 'NORMAL',
    "patientId" UUID,
    "encounterId" UUID,
    "subjectType" TEXT,
    "subjectId" UUID,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "assigneeType" "TaskAssigneeType" NOT NULL DEFAULT 'USER',
    "assigneeUserId" UUID,
    "assigneeTeamKey" TEXT,
    "dueAt" TIMESTAMP(3),
    "slaState" "TaskSlaState" NOT NULL DEFAULT 'OK',
    "expiresAt" TIMESTAMP(3),
    "sourceEventId" TEXT,
    "completedAt" TIMESTAMP(3),
    "completedById" UUID,
    "outcome" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MessageThread" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "kind" "ThreadKind" NOT NULL DEFAULT 'STAFF',
    "patientId" UUID,
    "subject" TEXT NOT NULL,
    "lastMessageAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MessageThread_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Message" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "threadId" UUID NOT NULL,
    "senderType" "MessageSenderType" NOT NULL DEFAULT 'USER',
    "senderUserId" UUID,
    "senderPatientId" UUID,
    "body" TEXT NOT NULL,
    "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Message_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChargeItem" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "facilityId" UUID NOT NULL,
    "encounterId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL DEFAULT 'http://www.ama-assn.org/go/cpt',
    "display" TEXT NOT NULL,
    "modifiers" TEXT[],
    "units" DECIMAL(9,3) NOT NULL DEFAULT 1,
    "unitPriceCents" INTEGER NOT NULL,
    "totalPriceCents" INTEGER NOT NULL,
    "diagnosisPointers" INTEGER[],
    "renderingProviderId" UUID NOT NULL,
    "supervisingProviderId" UUID,
    "placeOfServiceCode" TEXT,
    "serviceDate" DATE NOT NULL,
    "status" "ChargeItemStatus" NOT NULL DEFAULT 'OPEN',
    "voidReason" TEXT,
    "voidedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ChargeItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Claim" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID NOT NULL,
    "coverageId" UUID NOT NULL,
    "payerId" UUID NOT NULL,
    "status" "ClaimStatus" NOT NULL DEFAULT 'DRAFT',
    "frequency" "ClaimFrequency" NOT NULL DEFAULT 'ORIGINAL',
    "diagnosisCodes" TEXT[],
    "totalChargedCents" INTEGER NOT NULL DEFAULT 0,
    "totalPaidCents" INTEGER NOT NULL DEFAULT 0,
    "totalAdjustedCents" INTEGER NOT NULL DEFAULT 0,
    "patientResponsibilityCents" INTEGER NOT NULL DEFAULT 0,
    "secondaryOfId" UUID,
    "priorClaimId" UUID,
    "controlNumbers" JSONB NOT NULL DEFAULT '{}',
    "snapshot" JSONB NOT NULL DEFAULT '{}',
    "statusReason" TEXT,
    "submittedAt" TIMESTAMP(3),
    "acknowledgedAt" TIMESTAMP(3),
    "adjudicatedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Claim_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClaimLine" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "claimId" UUID NOT NULL,
    "chargeItemId" UUID NOT NULL,
    "sequence" INTEGER NOT NULL,
    "code" TEXT NOT NULL,
    "codeSystem" TEXT NOT NULL DEFAULT 'http://www.ama-assn.org/go/cpt',
    "modifiers" TEXT[],
    "units" DECIMAL(9,3) NOT NULL DEFAULT 1,
    "chargedCents" INTEGER NOT NULL,
    "allowedCents" INTEGER,
    "paidCents" INTEGER NOT NULL DEFAULT 0,
    "adjustedCents" INTEGER NOT NULL DEFAULT 0,
    "diagnosisPointers" INTEGER[],
    "serviceDateFrom" DATE NOT NULL,
    "serviceDateTo" DATE,
    "statusReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ClaimLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClaimStatusHistory" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "claimId" UUID NOT NULL,
    "status" "ClaimStatus" NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "source" TEXT NOT NULL,
    "detail" JSONB,
    "byUserId" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ClaimStatusHistory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payment" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID,
    "payerId" UUID,
    "remittanceId" UUID,
    "source" "PaymentSource" NOT NULL DEFAULT 'PATIENT',
    "method" "PaymentMethod" NOT NULL DEFAULT 'CARD',
    "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    "amountCents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "reference" TEXT,
    "adapterRef" TEXT,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "postedAt" TIMESTAMP(3),
    "postedById" UUID,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PaymentAllocation" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "paymentId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "claimId" UUID,
    "claimLineId" UUID,
    "chargeItemId" UUID,
    "amountCents" INTEGER NOT NULL,
    "adjustmentGroupCode" TEXT,
    "adjustmentReasonCode" TEXT,
    "appliedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PaymentAllocation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Remittance" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "payerId" UUID NOT NULL,
    "status" "RemittanceStatus" NOT NULL DEFAULT 'RECEIVED',
    "checkOrEftNumber" TEXT,
    "totalPaidCents" INTEGER NOT NULL DEFAULT 0,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "paidAt" TIMESTAMP(3),
    "rawStorageKey" TEXT,
    "parsed" JSONB,
    "exceptionCount" INTEGER NOT NULL DEFAULT 0,
    "postedAt" TIMESTAMP(3),
    "postedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Remittance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RemittanceLine" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "remittanceId" UUID NOT NULL,
    "claimId" UUID,
    "claimLineId" UUID,
    "sequence" INTEGER NOT NULL,
    "payerControlNumber" TEXT,
    "code" TEXT,
    "chargedCents" INTEGER NOT NULL DEFAULT 0,
    "allowedCents" INTEGER NOT NULL DEFAULT 0,
    "paidCents" INTEGER NOT NULL DEFAULT 0,
    "patientResponsibilityCents" INTEGER NOT NULL DEFAULT 0,
    "adjustmentGroupCode" TEXT,
    "adjustmentReasonCode" TEXT,
    "remarkCodes" TEXT[],
    "serviceDateFrom" DATE,
    "matched" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RemittanceLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Statement" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "status" "StatementStatus" NOT NULL DEFAULT 'DRAFT',
    "balanceCents" INTEGER NOT NULL,
    "dunningCycle" INTEGER NOT NULL DEFAULT 1,
    "periodStart" DATE,
    "periodEnd" DATE,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deliveredVia" "StatementDelivery",
    "deliveredAt" TIMESTAMP(3),
    "pdfStorageKey" TEXT,
    "payLinkToken" TEXT,
    "payLinkExpiresAt" TIMESTAMP(3),
    "paidAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Statement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FormDefinition" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "status" "FormStatus" NOT NULL DEFAULT 'DRAFT',
    "title" TEXT NOT NULL,
    "description" TEXT,
    "bindTo" "FormBinding" NOT NULL DEFAULT 'ENCOUNTER',
    "definition" JSONB NOT NULL DEFAULT '{}',
    "compiled" JSONB,
    "promotionManifest" JSONB,
    "publishedAt" TIMESTAMP(3),
    "publishedById" UUID,
    "retiredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FormDefinition_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FormSubmission" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "formDefinitionId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "encounterId" UUID,
    "status" "FormSubmissionStatus" NOT NULL DEFAULT 'IN_PROGRESS',
    "values" JSONB NOT NULL DEFAULT '{}',
    "completedByType" "FormCompletedByType" NOT NULL DEFAULT 'USER',
    "completedByUserId" UUID,
    "completedAt" TIMESTAMP(3),
    "signedAt" TIMESTAMP(3),
    "signedById" UUID,
    "effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FormSubmission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FormPromotedValue" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "formSubmissionId" UUID NOT NULL,
    "formDefinitionId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "definitionKey" TEXT NOT NULL,
    "definitionVersion" INTEGER NOT NULL,
    "fieldKey" TEXT NOT NULL,
    "repeatIndex" INTEGER NOT NULL DEFAULT 0,
    "valueText" TEXT,
    "valueNumber" DECIMAL(18,6),
    "valueDate" TIMESTAMP(3),
    "valueBoolean" BOOLEAN,
    "valueCode" TEXT,
    "valueCodeSystem" TEXT,
    "valueQuantity" DECIMAL(18,6),
    "valueUnit" TEXT,
    "effectiveAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FormPromotedValue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TerminologyCode" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "system" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "display" TEXT NOT NULL,
    "version" TEXT NOT NULL DEFAULT '',
    "parentCode" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "properties" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TerminologyCode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConsentGrant" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "patientId" UUID NOT NULL,
    "scope" "ConsentScope" NOT NULL,
    "status" "ConsentStatus" NOT NULL DEFAULT 'ACTIVE',
    "relatedPersonId" UUID,
    "documentId" UUID,
    "formSubmissionId" UUID,
    "policyText" TEXT,
    "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "effectiveTo" TIMESTAMP(3),
    "revokedAt" TIMESTAMP(3),
    "revokedReason" TEXT,
    "recordedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ConsentGrant_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Organisation_slug_key" ON "Organisation"("slug");

-- CreateIndex
CREATE INDEX "Organisation_status_idx" ON "Organisation"("status");

-- CreateIndex
CREATE INDEX "Facility_tenantId_active_idx" ON "Facility"("tenantId", "active");

-- CreateIndex
CREATE UNIQUE INDEX "Facility_tenantId_code_key" ON "Facility"("tenantId", "code");

-- CreateIndex
CREATE INDEX "User_tenantId_isProvider_status_idx" ON "User"("tenantId", "isProvider", "status");

-- CreateIndex
CREATE INDEX "User_tenantId_familyName_givenName_idx" ON "User"("tenantId", "familyName", "givenName");

-- CreateIndex
CREATE UNIQUE INDEX "User_tenantId_email_key" ON "User"("tenantId", "email");

-- CreateIndex
CREATE INDEX "UserFacility_tenantId_facilityId_idx" ON "UserFacility"("tenantId", "facilityId");

-- CreateIndex
CREATE UNIQUE INDEX "UserFacility_userId_facilityId_key" ON "UserFacility"("userId", "facilityId");

-- CreateIndex
CREATE UNIQUE INDEX "Role_tenantId_key_key" ON "Role"("tenantId", "key");

-- CreateIndex
CREATE UNIQUE INDEX "Permission_tenantId_key_key" ON "Permission"("tenantId", "key");

-- CreateIndex
CREATE INDEX "RolePermission_tenantId_permissionId_idx" ON "RolePermission"("tenantId", "permissionId");

-- CreateIndex
CREATE UNIQUE INDEX "RolePermission_roleId_permissionId_key" ON "RolePermission"("roleId", "permissionId");

-- CreateIndex
CREATE INDEX "RoleAssignment_tenantId_roleId_idx" ON "RoleAssignment"("tenantId", "roleId");

-- CreateIndex
CREATE UNIQUE INDEX "RoleAssignment_userId_roleId_facilityId_key" ON "RoleAssignment"("userId", "roleId", "facilityId");

-- CreateIndex
CREATE INDEX "Patient_tenantId_familyName_givenName_idx" ON "Patient"("tenantId", "familyName", "givenName");

-- CreateIndex
CREATE INDEX "Patient_tenantId_birthDate_idx" ON "Patient"("tenantId", "birthDate");

-- CreateIndex
CREATE INDEX "Patient_tenantId_active_familyName_givenName_idx" ON "Patient"("tenantId", "active", "familyName", "givenName");

-- CreateIndex
CREATE INDEX "Patient_tenantId_primaryFacilityId_active_idx" ON "Patient"("tenantId", "primaryFacilityId", "active");

-- CreateIndex
CREATE UNIQUE INDEX "Patient_tenantId_mrn_key" ON "Patient"("tenantId", "mrn");

-- CreateIndex
CREATE INDEX "PatientIdentifier_tenantId_patientId_idx" ON "PatientIdentifier"("tenantId", "patientId");

-- CreateIndex
CREATE INDEX "PatientIdentifier_tenantId_value_idx" ON "PatientIdentifier"("tenantId", "value");

-- CreateIndex
CREATE UNIQUE INDEX "PatientIdentifier_tenantId_system_value_key" ON "PatientIdentifier"("tenantId", "system", "value");

-- CreateIndex
CREATE INDEX "RelatedPerson_tenantId_patientId_active_idx" ON "RelatedPerson"("tenantId", "patientId", "active");

-- CreateIndex
CREATE INDEX "Payer_tenantId_active_idx" ON "Payer"("tenantId", "active");

-- CreateIndex
CREATE UNIQUE INDEX "Payer_tenantId_name_key" ON "Payer"("tenantId", "name");

-- CreateIndex
CREATE INDEX "Coverage_tenantId_patientId_rank_idx" ON "Coverage"("tenantId", "patientId", "rank");

-- CreateIndex
CREATE INDEX "Coverage_tenantId_payerId_status_idx" ON "Coverage"("tenantId", "payerId", "status");

-- CreateIndex
CREATE INDEX "Document_tenantId_patientId_category_idx" ON "Document"("tenantId", "patientId", "category");

-- CreateIndex
CREATE INDEX "Document_tenantId_status_receivedAt_idx" ON "Document"("tenantId", "status", "receivedAt");

-- CreateIndex
CREATE INDEX "Document_tenantId_encounterId_idx" ON "Document"("tenantId", "encounterId");

-- CreateIndex
CREATE INDEX "Appointment_tenantId_facilityId_start_idx" ON "Appointment"("tenantId", "facilityId", "start");

-- CreateIndex
CREATE INDEX "Appointment_tenantId_facilityId_status_start_idx" ON "Appointment"("tenantId", "facilityId", "status", "start");

-- CreateIndex
CREATE INDEX "Appointment_tenantId_providerId_start_idx" ON "Appointment"("tenantId", "providerId", "start");

-- CreateIndex
CREATE INDEX "Appointment_tenantId_patientId_start_idx" ON "Appointment"("tenantId", "patientId", "start");

-- CreateIndex
CREATE INDEX "Appointment_tenantId_recurrenceGroupId_idx" ON "Appointment"("tenantId", "recurrenceGroupId");

-- CreateIndex
CREATE INDEX "AppointmentStatusHistory_tenantId_appointmentId_occurredAt_idx" ON "AppointmentStatusHistory"("tenantId", "appointmentId", "occurredAt");

-- CreateIndex
CREATE INDEX "AppointmentStatusHistory_tenantId_status_occurredAt_idx" ON "AppointmentStatusHistory"("tenantId", "status", "occurredAt");

-- CreateIndex
CREATE UNIQUE INDEX "Encounter_appointmentId_key" ON "Encounter"("appointmentId");

-- CreateIndex
CREATE INDEX "Encounter_tenantId_patientId_startedAt_idx" ON "Encounter"("tenantId", "patientId", "startedAt");

-- CreateIndex
CREATE INDEX "Encounter_tenantId_facilityId_status_startedAt_idx" ON "Encounter"("tenantId", "facilityId", "status", "startedAt");

-- CreateIndex
CREATE INDEX "Encounter_tenantId_providerId_startedAt_idx" ON "Encounter"("tenantId", "providerId", "startedAt");

-- CreateIndex
CREATE INDEX "ClinicalNote_tenantId_state_createdAt_idx" ON "ClinicalNote"("tenantId", "state", "createdAt");

-- CreateIndex
CREATE INDEX "ClinicalNote_tenantId_patientId_createdAt_idx" ON "ClinicalNote"("tenantId", "patientId", "createdAt");

-- CreateIndex
CREATE INDEX "ClinicalNote_tenantId_encounterId_idx" ON "ClinicalNote"("tenantId", "encounterId");

-- CreateIndex
CREATE INDEX "ClinicalNote_tenantId_authorId_state_idx" ON "ClinicalNote"("tenantId", "authorId", "state");

-- CreateIndex
CREATE INDEX "NoteAddendum_tenantId_noteId_createdAt_idx" ON "NoteAddendum"("tenantId", "noteId", "createdAt");

-- CreateIndex
CREATE INDEX "Condition_tenantId_patientId_clinicalStatus_idx" ON "Condition"("tenantId", "patientId", "clinicalStatus");

-- CreateIndex
CREATE INDEX "Condition_tenantId_patientId_category_recordedAt_idx" ON "Condition"("tenantId", "patientId", "category", "recordedAt");

-- CreateIndex
CREATE INDEX "Condition_tenantId_code_idx" ON "Condition"("tenantId", "code");

-- CreateIndex
CREATE INDEX "MedicationStatement_tenantId_patientId_status_idx" ON "MedicationStatement"("tenantId", "patientId", "status");

-- CreateIndex
CREATE INDEX "MedicationRequest_tenantId_patientId_status_idx" ON "MedicationRequest"("tenantId", "patientId", "status");

-- CreateIndex
CREATE INDEX "MedicationRequest_tenantId_status_writtenAt_idx" ON "MedicationRequest"("tenantId", "status", "writtenAt");

-- CreateIndex
CREATE INDEX "MedicationRequest_tenantId_prescriberId_status_idx" ON "MedicationRequest"("tenantId", "prescriberId", "status");

-- CreateIndex
CREATE INDEX "AllergyIntolerance_tenantId_patientId_clinicalStatus_idx" ON "AllergyIntolerance"("tenantId", "patientId", "clinicalStatus");

-- CreateIndex
CREATE INDEX "AllergyIntolerance_tenantId_patientId_criticality_idx" ON "AllergyIntolerance"("tenantId", "patientId", "criticality");

-- CreateIndex
CREATE INDEX "Immunization_tenantId_patientId_administeredAt_idx" ON "Immunization"("tenantId", "patientId", "administeredAt");

-- CreateIndex
CREATE INDEX "Immunization_tenantId_cvxCode_administeredAt_idx" ON "Immunization"("tenantId", "cvxCode", "administeredAt");

-- CreateIndex
CREATE INDEX "Observation_tenantId_patientId_effectiveAt_idx" ON "Observation"("tenantId", "patientId", "effectiveAt");

-- CreateIndex
CREATE INDEX "Observation_tenantId_patientId_loincCode_effectiveAt_idx" ON "Observation"("tenantId", "patientId", "loincCode", "effectiveAt");

-- CreateIndex
CREATE INDEX "Observation_tenantId_patientId_category_effectiveAt_idx" ON "Observation"("tenantId", "patientId", "category", "effectiveAt");

-- CreateIndex
CREATE INDEX "Observation_tenantId_encounterId_idx" ON "Observation"("tenantId", "encounterId");

-- CreateIndex
CREATE INDEX "ServiceRequest_tenantId_status_requestedAt_idx" ON "ServiceRequest"("tenantId", "status", "requestedAt");

-- CreateIndex
CREATE INDEX "ServiceRequest_tenantId_patientId_requestedAt_idx" ON "ServiceRequest"("tenantId", "patientId", "requestedAt");

-- CreateIndex
CREATE INDEX "ServiceRequest_tenantId_orderedById_status_idx" ON "ServiceRequest"("tenantId", "orderedById", "status");

-- CreateIndex
CREATE INDEX "ServiceRequest_tenantId_category_status_priority_idx" ON "ServiceRequest"("tenantId", "category", "status", "priority");

-- CreateIndex
CREATE INDEX "Specimen_tenantId_patientId_collectedAt_idx" ON "Specimen"("tenantId", "patientId", "collectedAt");

-- CreateIndex
CREATE INDEX "Specimen_tenantId_serviceRequestId_idx" ON "Specimen"("tenantId", "serviceRequestId");

-- CreateIndex
CREATE UNIQUE INDEX "Specimen_tenantId_accessionNumber_key" ON "Specimen"("tenantId", "accessionNumber");

-- CreateIndex
CREATE INDEX "DiagnosticReport_tenantId_patientId_issuedAt_idx" ON "DiagnosticReport"("tenantId", "patientId", "issuedAt");

-- CreateIndex
CREATE INDEX "DiagnosticReport_tenantId_status_issuedAt_idx" ON "DiagnosticReport"("tenantId", "status", "issuedAt");

-- CreateIndex
CREATE INDEX "DiagnosticReport_tenantId_reviewedAt_abnormalFlag_idx" ON "DiagnosticReport"("tenantId", "reviewedAt", "abnormalFlag");

-- CreateIndex
CREATE INDEX "DiagnosticReport_tenantId_serviceRequestId_idx" ON "DiagnosticReport"("tenantId", "serviceRequestId");

-- CreateIndex
CREATE INDEX "ResultObservation_tenantId_patientId_loincCode_effectiveAt_idx" ON "ResultObservation"("tenantId", "patientId", "loincCode", "effectiveAt");

-- CreateIndex
CREATE INDEX "ResultObservation_tenantId_patientId_effectiveAt_idx" ON "ResultObservation"("tenantId", "patientId", "effectiveAt");

-- CreateIndex
CREATE UNIQUE INDEX "ResultObservation_diagnosticReportId_sequence_key" ON "ResultObservation"("diagnosticReportId", "sequence");

-- CreateIndex
CREATE INDEX "Task_tenantId_assigneeType_assigneeUserId_status_idx" ON "Task"("tenantId", "assigneeType", "assigneeUserId", "status");

-- CreateIndex
CREATE INDEX "Task_tenantId_assigneeTeamKey_status_idx" ON "Task"("tenantId", "assigneeTeamKey", "status");

-- CreateIndex
CREATE INDEX "Task_tenantId_type_status_dueAt_idx" ON "Task"("tenantId", "type", "status", "dueAt");

-- CreateIndex
CREATE INDEX "Task_tenantId_status_slaState_dueAt_idx" ON "Task"("tenantId", "status", "slaState", "dueAt");

-- CreateIndex
CREATE INDEX "Task_tenantId_patientId_status_idx" ON "Task"("tenantId", "patientId", "status");

-- CreateIndex
CREATE INDEX "Task_tenantId_expiresAt_idx" ON "Task"("tenantId", "expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "Task_tenantId_sourceEventId_type_key" ON "Task"("tenantId", "sourceEventId", "type");

-- CreateIndex
CREATE INDEX "MessageThread_tenantId_kind_lastMessageAt_idx" ON "MessageThread"("tenantId", "kind", "lastMessageAt");

-- CreateIndex
CREATE INDEX "MessageThread_tenantId_patientId_lastMessageAt_idx" ON "MessageThread"("tenantId", "patientId", "lastMessageAt");

-- CreateIndex
CREATE INDEX "Message_tenantId_threadId_sentAt_idx" ON "Message"("tenantId", "threadId", "sentAt");

-- CreateIndex
CREATE INDEX "Message_tenantId_senderUserId_sentAt_idx" ON "Message"("tenantId", "senderUserId", "sentAt");

-- CreateIndex
CREATE INDEX "ChargeItem_tenantId_encounterId_idx" ON "ChargeItem"("tenantId", "encounterId");

-- CreateIndex
CREATE INDEX "ChargeItem_tenantId_patientId_status_idx" ON "ChargeItem"("tenantId", "patientId", "status");

-- CreateIndex
CREATE INDEX "ChargeItem_tenantId_status_serviceDate_idx" ON "ChargeItem"("tenantId", "status", "serviceDate");

-- CreateIndex
CREATE INDEX "Claim_tenantId_status_submittedAt_idx" ON "Claim"("tenantId", "status", "submittedAt");

-- CreateIndex
CREATE INDEX "Claim_tenantId_status_createdAt_idx" ON "Claim"("tenantId", "status", "createdAt");

-- CreateIndex
CREATE INDEX "Claim_tenantId_patientId_createdAt_idx" ON "Claim"("tenantId", "patientId", "createdAt");

-- CreateIndex
CREATE INDEX "Claim_tenantId_payerId_status_idx" ON "Claim"("tenantId", "payerId", "status");

-- CreateIndex
CREATE INDEX "ClaimLine_tenantId_claimId_idx" ON "ClaimLine"("tenantId", "claimId");

-- CreateIndex
CREATE INDEX "ClaimLine_tenantId_chargeItemId_idx" ON "ClaimLine"("tenantId", "chargeItemId");

-- CreateIndex
CREATE UNIQUE INDEX "ClaimLine_claimId_sequence_key" ON "ClaimLine"("claimId", "sequence");

-- CreateIndex
CREATE INDEX "ClaimStatusHistory_tenantId_claimId_occurredAt_idx" ON "ClaimStatusHistory"("tenantId", "claimId", "occurredAt");

-- CreateIndex
CREATE INDEX "ClaimStatusHistory_tenantId_status_occurredAt_idx" ON "ClaimStatusHistory"("tenantId", "status", "occurredAt");

-- CreateIndex
CREATE INDEX "Payment_tenantId_patientId_receivedAt_idx" ON "Payment"("tenantId", "patientId", "receivedAt");

-- CreateIndex
CREATE INDEX "Payment_tenantId_status_receivedAt_idx" ON "Payment"("tenantId", "status", "receivedAt");

-- CreateIndex
CREATE INDEX "Payment_tenantId_remittanceId_idx" ON "Payment"("tenantId", "remittanceId");

-- CreateIndex
CREATE INDEX "PaymentAllocation_tenantId_paymentId_idx" ON "PaymentAllocation"("tenantId", "paymentId");

-- CreateIndex
CREATE INDEX "PaymentAllocation_tenantId_patientId_appliedAt_idx" ON "PaymentAllocation"("tenantId", "patientId", "appliedAt");

-- CreateIndex
CREATE INDEX "PaymentAllocation_tenantId_claimId_idx" ON "PaymentAllocation"("tenantId", "claimId");

-- CreateIndex
CREATE INDEX "Remittance_tenantId_status_receivedAt_idx" ON "Remittance"("tenantId", "status", "receivedAt");

-- CreateIndex
CREATE INDEX "Remittance_tenantId_payerId_receivedAt_idx" ON "Remittance"("tenantId", "payerId", "receivedAt");

-- CreateIndex
CREATE INDEX "RemittanceLine_tenantId_claimId_idx" ON "RemittanceLine"("tenantId", "claimId");

-- CreateIndex
CREATE INDEX "RemittanceLine_tenantId_remittanceId_matched_idx" ON "RemittanceLine"("tenantId", "remittanceId", "matched");

-- CreateIndex
CREATE UNIQUE INDEX "RemittanceLine_remittanceId_sequence_key" ON "RemittanceLine"("remittanceId", "sequence");

-- CreateIndex
CREATE UNIQUE INDEX "Statement_payLinkToken_key" ON "Statement"("payLinkToken");

-- CreateIndex
CREATE INDEX "Statement_tenantId_patientId_generatedAt_idx" ON "Statement"("tenantId", "patientId", "generatedAt");

-- CreateIndex
CREATE INDEX "Statement_tenantId_status_generatedAt_idx" ON "Statement"("tenantId", "status", "generatedAt");

-- CreateIndex
CREATE INDEX "FormDefinition_tenantId_bindTo_status_idx" ON "FormDefinition"("tenantId", "bindTo", "status");

-- CreateIndex
CREATE INDEX "FormDefinition_tenantId_key_status_idx" ON "FormDefinition"("tenantId", "key", "status");

-- CreateIndex
CREATE UNIQUE INDEX "FormDefinition_tenantId_key_version_key" ON "FormDefinition"("tenantId", "key", "version");

-- CreateIndex
CREATE INDEX "FormSubmission_tenantId_patientId_effectiveAt_idx" ON "FormSubmission"("tenantId", "patientId", "effectiveAt");

-- CreateIndex
CREATE INDEX "FormSubmission_tenantId_formDefinitionId_createdAt_idx" ON "FormSubmission"("tenantId", "formDefinitionId", "createdAt");

-- CreateIndex
CREATE INDEX "FormSubmission_tenantId_encounterId_idx" ON "FormSubmission"("tenantId", "encounterId");

-- CreateIndex
CREATE INDEX "FormPromotedValue_tenantId_definitionKey_fieldKey_effective_idx" ON "FormPromotedValue"("tenantId", "definitionKey", "fieldKey", "effectiveAt");

-- CreateIndex
CREATE INDEX "FormPromotedValue_tenantId_patientId_fieldKey_effectiveAt_idx" ON "FormPromotedValue"("tenantId", "patientId", "fieldKey", "effectiveAt");

-- CreateIndex
CREATE INDEX "FormPromotedValue_tenantId_formDefinitionId_idx" ON "FormPromotedValue"("tenantId", "formDefinitionId");

-- CreateIndex
CREATE UNIQUE INDEX "FormPromotedValue_formSubmissionId_fieldKey_repeatIndex_key" ON "FormPromotedValue"("formSubmissionId", "fieldKey", "repeatIndex");

-- CreateIndex
CREATE INDEX "TerminologyCode_tenantId_system_isActive_idx" ON "TerminologyCode"("tenantId", "system", "isActive");

-- CreateIndex
CREATE INDEX "TerminologyCode_tenantId_system_display_idx" ON "TerminologyCode"("tenantId", "system", "display");

-- CreateIndex
CREATE UNIQUE INDEX "TerminologyCode_tenantId_system_code_version_key" ON "TerminologyCode"("tenantId", "system", "code", "version");

-- CreateIndex
CREATE INDEX "ConsentGrant_tenantId_patientId_scope_status_idx" ON "ConsentGrant"("tenantId", "patientId", "scope", "status");

-- CreateIndex
CREATE INDEX "ConsentGrant_tenantId_status_effectiveTo_idx" ON "ConsentGrant"("tenantId", "status", "effectiveTo");

-- CreateIndex
CREATE INDEX "AuditEvent_tenantId_targetType_targetId_idx" ON "AuditEvent"("tenantId", "targetType", "targetId");

-- CreateIndex
CREATE INDEX "AuditEvent_tenantId_patientId_occurredAt_idx" ON "AuditEvent"("tenantId", "patientId", "occurredAt");

-- CreateIndex
CREATE INDEX "AuditEvent_tenantId_occurredAt_idx" ON "AuditEvent"("tenantId", "occurredAt");

-- CreateIndex
CREATE INDEX "AuditEvent_tenantId_actorId_occurredAt_idx" ON "AuditEvent"("tenantId", "actorId", "occurredAt");

-- CreateIndex
CREATE INDEX "AuditEvent_tenantId_breakglass_occurredAt_idx" ON "AuditEvent"("tenantId", "breakglass", "occurredAt");

-- CreateIndex
CREATE UNIQUE INDEX "AuditEvent_tenantId_seq_key" ON "AuditEvent"("tenantId", "seq");

-- CreateIndex
CREATE UNIQUE INDEX "AuditEvent_tenantId_hash_key" ON "AuditEvent"("tenantId", "hash");

-- AddForeignKey
ALTER TABLE "Facility" ADD CONSTRAINT "Facility_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFacility" ADD CONSTRAINT "UserFacility_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFacility" ADD CONSTRAINT "UserFacility_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFacility" ADD CONSTRAINT "UserFacility_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "Facility"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Role" ADD CONSTRAINT "Role_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Permission" ADD CONSTRAINT "Permission_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoleAssignment" ADD CONSTRAINT "RoleAssignment_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoleAssignment" ADD CONSTRAINT "RoleAssignment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoleAssignment" ADD CONSTRAINT "RoleAssignment_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Patient" ADD CONSTRAINT "Patient_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Patient" ADD CONSTRAINT "Patient_primaryFacilityId_fkey" FOREIGN KEY ("primaryFacilityId") REFERENCES "Facility"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PatientIdentifier" ADD CONSTRAINT "PatientIdentifier_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PatientIdentifier" ADD CONSTRAINT "PatientIdentifier_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RelatedPerson" ADD CONSTRAINT "RelatedPerson_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RelatedPerson" ADD CONSTRAINT "RelatedPerson_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payer" ADD CONSTRAINT "Payer_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Coverage" ADD CONSTRAINT "Coverage_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Coverage" ADD CONSTRAINT "Coverage_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Coverage" ADD CONSTRAINT "Coverage_payerId_fkey" FOREIGN KEY ("payerId") REFERENCES "Payer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "Facility"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppointmentStatusHistory" ADD CONSTRAINT "AppointmentStatusHistory_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppointmentStatusHistory" ADD CONSTRAINT "AppointmentStatusHistory_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "Facility"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClinicalNote" ADD CONSTRAINT "ClinicalNote_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClinicalNote" ADD CONSTRAINT "ClinicalNote_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClinicalNote" ADD CONSTRAINT "ClinicalNote_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClinicalNote" ADD CONSTRAINT "ClinicalNote_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NoteAddendum" ADD CONSTRAINT "NoteAddendum_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NoteAddendum" ADD CONSTRAINT "NoteAddendum_noteId_fkey" FOREIGN KEY ("noteId") REFERENCES "ClinicalNote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NoteAddendum" ADD CONSTRAINT "NoteAddendum_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Condition" ADD CONSTRAINT "Condition_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Condition" ADD CONSTRAINT "Condition_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Condition" ADD CONSTRAINT "Condition_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationStatement" ADD CONSTRAINT "MedicationStatement_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationStatement" ADD CONSTRAINT "MedicationStatement_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationStatement" ADD CONSTRAINT "MedicationStatement_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationRequest" ADD CONSTRAINT "MedicationRequest_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationRequest" ADD CONSTRAINT "MedicationRequest_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationRequest" ADD CONSTRAINT "MedicationRequest_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicationRequest" ADD CONSTRAINT "MedicationRequest_prescriberId_fkey" FOREIGN KEY ("prescriberId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AllergyIntolerance" ADD CONSTRAINT "AllergyIntolerance_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AllergyIntolerance" ADD CONSTRAINT "AllergyIntolerance_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Immunization" ADD CONSTRAINT "Immunization_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Immunization" ADD CONSTRAINT "Immunization_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Immunization" ADD CONSTRAINT "Immunization_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Observation" ADD CONSTRAINT "Observation_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Observation" ADD CONSTRAINT "Observation_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Observation" ADD CONSTRAINT "Observation_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Observation" ADD CONSTRAINT "Observation_formSubmissionId_fkey" FOREIGN KEY ("formSubmissionId") REFERENCES "FormSubmission"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceRequest" ADD CONSTRAINT "ServiceRequest_orderedById_fkey" FOREIGN KEY ("orderedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Specimen" ADD CONSTRAINT "Specimen_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Specimen" ADD CONSTRAINT "Specimen_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Specimen" ADD CONSTRAINT "Specimen_serviceRequestId_fkey" FOREIGN KEY ("serviceRequestId") REFERENCES "ServiceRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DiagnosticReport" ADD CONSTRAINT "DiagnosticReport_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DiagnosticReport" ADD CONSTRAINT "DiagnosticReport_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DiagnosticReport" ADD CONSTRAINT "DiagnosticReport_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DiagnosticReport" ADD CONSTRAINT "DiagnosticReport_serviceRequestId_fkey" FOREIGN KEY ("serviceRequestId") REFERENCES "ServiceRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DiagnosticReport" ADD CONSTRAINT "DiagnosticReport_specimenId_fkey" FOREIGN KEY ("specimenId") REFERENCES "Specimen"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ResultObservation" ADD CONSTRAINT "ResultObservation_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ResultObservation" ADD CONSTRAINT "ResultObservation_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ResultObservation" ADD CONSTRAINT "ResultObservation_diagnosticReportId_fkey" FOREIGN KEY ("diagnosticReportId") REFERENCES "DiagnosticReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_assigneeUserId_fkey" FOREIGN KEY ("assigneeUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MessageThread" ADD CONSTRAINT "MessageThread_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MessageThread" ADD CONSTRAINT "MessageThread_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_threadId_fkey" FOREIGN KEY ("threadId") REFERENCES "MessageThread"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_senderUserId_fkey" FOREIGN KEY ("senderUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChargeItem" ADD CONSTRAINT "ChargeItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChargeItem" ADD CONSTRAINT "ChargeItem_facilityId_fkey" FOREIGN KEY ("facilityId") REFERENCES "Facility"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChargeItem" ADD CONSTRAINT "ChargeItem_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChargeItem" ADD CONSTRAINT "ChargeItem_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChargeItem" ADD CONSTRAINT "ChargeItem_renderingProviderId_fkey" FOREIGN KEY ("renderingProviderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_coverageId_fkey" FOREIGN KEY ("coverageId") REFERENCES "Coverage"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_payerId_fkey" FOREIGN KEY ("payerId") REFERENCES "Payer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_secondaryOfId_fkey" FOREIGN KEY ("secondaryOfId") REFERENCES "Claim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_priorClaimId_fkey" FOREIGN KEY ("priorClaimId") REFERENCES "Claim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClaimLine" ADD CONSTRAINT "ClaimLine_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClaimLine" ADD CONSTRAINT "ClaimLine_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClaimLine" ADD CONSTRAINT "ClaimLine_chargeItemId_fkey" FOREIGN KEY ("chargeItemId") REFERENCES "ChargeItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClaimStatusHistory" ADD CONSTRAINT "ClaimStatusHistory_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClaimStatusHistory" ADD CONSTRAINT "ClaimStatusHistory_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_payerId_fkey" FOREIGN KEY ("payerId") REFERENCES "Payer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_remittanceId_fkey" FOREIGN KEY ("remittanceId") REFERENCES "Remittance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_claimLineId_fkey" FOREIGN KEY ("claimLineId") REFERENCES "ClaimLine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_chargeItemId_fkey" FOREIGN KEY ("chargeItemId") REFERENCES "ChargeItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Remittance" ADD CONSTRAINT "Remittance_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Remittance" ADD CONSTRAINT "Remittance_payerId_fkey" FOREIGN KEY ("payerId") REFERENCES "Payer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RemittanceLine" ADD CONSTRAINT "RemittanceLine_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RemittanceLine" ADD CONSTRAINT "RemittanceLine_remittanceId_fkey" FOREIGN KEY ("remittanceId") REFERENCES "Remittance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RemittanceLine" ADD CONSTRAINT "RemittanceLine_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RemittanceLine" ADD CONSTRAINT "RemittanceLine_claimLineId_fkey" FOREIGN KEY ("claimLineId") REFERENCES "ClaimLine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Statement" ADD CONSTRAINT "Statement_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Statement" ADD CONSTRAINT "Statement_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormDefinition" ADD CONSTRAINT "FormDefinition_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormSubmission" ADD CONSTRAINT "FormSubmission_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormSubmission" ADD CONSTRAINT "FormSubmission_formDefinitionId_fkey" FOREIGN KEY ("formDefinitionId") REFERENCES "FormDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormSubmission" ADD CONSTRAINT "FormSubmission_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormSubmission" ADD CONSTRAINT "FormSubmission_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormPromotedValue" ADD CONSTRAINT "FormPromotedValue_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormPromotedValue" ADD CONSTRAINT "FormPromotedValue_formSubmissionId_fkey" FOREIGN KEY ("formSubmissionId") REFERENCES "FormSubmission"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormPromotedValue" ADD CONSTRAINT "FormPromotedValue_formDefinitionId_fkey" FOREIGN KEY ("formDefinitionId") REFERENCES "FormDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FormPromotedValue" ADD CONSTRAINT "FormPromotedValue_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TerminologyCode" ADD CONSTRAINT "TerminologyCode_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentGrant" ADD CONSTRAINT "ConsentGrant_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentGrant" ADD CONSTRAINT "ConsentGrant_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentGrant" ADD CONSTRAINT "ConsentGrant_relatedPersonId_fkey" FOREIGN KEY ("relatedPersonId") REFERENCES "RelatedPerson"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentGrant" ADD CONSTRAINT "ConsentGrant_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConsentGrant" ADD CONSTRAINT "ConsentGrant_formSubmissionId_fkey" FOREIGN KEY ("formSubmissionId") REFERENCES "FormSubmission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
