/**
 * What each role may do, mirrored from the API.
 *
 * GENERATED by `scripts/ci/capability-parity.mjs` from
 * `apps/api/src/policy/permissions.ts`. Do not edit: run `pnpm capabilities`.
 *
 * The staff application asks `/bff/v0/me` for this and uses the answer to stop
 * offering an action the server will refuse (#313). In the demonstration build
 * there is no server to ask - `NEXT_PUBLIC_API_MODE=mock` is the documented
 * default - so the mock client answers from this table, and the demonstration
 * then behaves the way a deployment does rather than offering a biller "Sign
 * orders".
 *
 * Nothing here is a security boundary. Every route enforces its own permission;
 * this only decides what the interface offers.
 */
export const ROLE_CAPABILITIES: Readonly<Record<string, readonly string[]>> = {
  admin: [
    'patient.read',
    'patient.write',
    'patient.breakGlass',
    'appointment.read',
    'appointment.write',
    'telehealth.join',
    'encounter.read',
    'encounter.write',
    'document.read',
    'document.write',
    'order.read',
    'order.write',
    'result.read',
    'result.write',
    'message.read',
    'message.write',
    'coverage.read',
    'coverage.write',
    'charge.read',
    'charge.write',
    'claim.read',
    'claim.write',
    'payment.read',
    'payment.write',
    'task.read',
    'task.write',
    'form.read',
    'form.write',
    'user.read',
    'user.write',
    'role.read',
    'role.write',
    'facility.read',
    'facility.write',
    'terminology.read',
    'terminology.write',
    'inventory.read',
    'inventory.write',
    'inventory.adjust',
    'audit.read',
    'facility.all',
  ],
  clinician: [
    'patient.read',
    'patient.write',
    'patient.breakGlass',
    'appointment.read',
    'appointment.write',
    'telehealth.join',
    'encounter.read',
    'encounter.write',
    'document.read',
    'document.write',
    'order.read',
    'order.write',
    'result.read',
    'result.write',
    'message.read',
    'message.write',
    'coverage.read',
    'charge.read',
    'charge.write',
    'task.read',
    'task.write',
    'form.read',
    'form.write',
    'user.read',
    'facility.read',
    'terminology.read',
    'inventory.read',
    'inventory.write',
  ],
  'front-desk': [
    'patient.read',
    'patient.write',
    'patient.breakGlass',
    'appointment.read',
    'appointment.write',
    'telehealth.join',
    'encounter.read',
    'document.read',
    'document.write',
    'message.read',
    'message.write',
    'coverage.read',
    'coverage.write',
    'task.read',
    'task.write',
    'form.read',
    'payment.read',
    'user.read',
    'facility.read',
    'terminology.read',
    'inventory.read',
  ],
  biller: [
    'patient.read',
    'appointment.read',
    'encounter.read',
    'document.read',
    'coverage.read',
    'coverage.write',
    'charge.read',
    'charge.write',
    'claim.read',
    'claim.write',
    'payment.read',
    'payment.write',
    'task.read',
    'task.write',
    'user.read',
    'facility.read',
    'terminology.read',
  ],
  'patient-portal': [
    'patient.read',
    'appointment.read',
    'appointment.write',
    'encounter.read',
    'document.read',
    'result.read',
    'message.read',
    'message.write',
    'coverage.read',
    'form.read',
    'form.write',
    'payment.read',
  ],
  'stock-keeper': ['inventory.read', 'inventory.write', 'inventory.adjust', 'facility.read'],
  auditor: ['audit.read', 'facility.read'],
  'read-only': [
    'patient.read',
    'appointment.read',
    'encounter.read',
    'document.read',
    'order.read',
    'result.read',
    'message.read',
    'coverage.read',
    'charge.read',
    'claim.read',
    'payment.read',
    'task.read',
    'form.read',
    'user.read',
    'role.read',
    'facility.read',
    'terminology.read',
    'inventory.read',
  ],
};

/**
 * The permissions a principal holding `roles` has, as the API would resolve
 * them.
 *
 * A role this table does not know contributes nothing rather than throwing,
 * which is the API's own rule: a deployment that renames a role should lose
 * access, not break the interface.
 */
export function capabilitiesForRoles(roles: readonly string[]): string[] {
  const held = new Set<string>();
  for (const role of roles) {
    for (const capability of ROLE_CAPABILITIES[role] ?? []) held.add(capability);
  }
  return [...held].sort((a, b) => a.localeCompare(b));
}
