/**
 * The data layer's public surface. Screens import from `@/lib/api` and nothing
 * deeper, so the transport, the fixtures and the hook shape can all change
 * without touching a screen.
 */
export { api } from './api';
export { ApiError, BFF_BASE_PATH, createHttpClient, requestJson, toSearchParams } from './client';
export type { ApiClientConfig, ApiErrorKind } from './client';
export { API_BASE_URL, API_MODE, IS_MOCK_MODE, resolveApiMode } from './config';
export type { ApiMode } from './config';
export { createMockClient, filterAppointments, filterPatients } from './mock/client';
export {
  MOCK_APPOINTMENTS,
  MOCK_CLINIC_DAY,
  MOCK_COVERAGES,
  MOCK_FACILITY,
  MOCK_NOW,
  MOCK_PATIENTS,
  MOCK_PROVIDERS,
  MOCK_ROOMS,
  MOCK_STATUS_SINCE,
  mockCoveragesForPatient,
  mockPatientById,
  mockProviderName,
  mockStatusSince,
  mockVerifyEligibility,
} from './mock/fixtures';
export type {
  CoveragePriority,
  EligibilityOutcome,
  MockCoverage,
  MockEligibilityResult,
} from './mock/fixtures';
export {
  queryKey,
  useApiQuery,
  useAppointment,
  useAppointments,
  usePatient,
  usePatients,
} from './hooks';
export type { AsyncState, AsyncStatus, HookOptions } from './hooks';
export * from './types';

/* Admin, developer platform and reports. The routes behind these do not exist in
   `apps/api` yet, so the client is fixture-only for now and the contract is
   written the way the API will answer. */
export {
  adminApi,
  AUDIT_ACTIONS,
  INTEGRATION_STATUSES,
  PURPOSES_OF_USE,
  STAFF_ROLES,
  STAFF_STATUSES,
  useApiKeys,
  useApiScopes,
  useAdminClientOption,
  useAuditEvents,
  useFacilities,
  useFormDefinitions,
  useFormFieldTypes,
  useIntegrations,
  usePermissionMatrix,
  usePracticeDashboard,
  useSmartApps,
  useStaffUsers,
  useVisitReport,
  useWebhooks,
} from './admin';
export type {
  AdminClient,
  AdminHookOptions,
  AgingBucket,
  ApiKey,
  ApiScope,
  AuditAction,
  AuditEvent,
  AuditQuery,
  ClaimFunnelStage,
  DashboardTile,
  Facility,
  FacilityHours,
  FormDefinition,
  FormField,
  FormFieldType,
  FormSection,
  Integration,
  IntegrationStatus,
  PermissionLevel,
  PermissionRow,
  PracticeDashboard,
  PurposeOfUse,
  SmartApp,
  SmartAppLaunch,
  StaffRole,
  StaffStatus,
  StaffUser,
  StaffUserQuery,
  UnsignedByProvider,
  VisitReport,
  VisitReportQuery,
  VisitReportRow,
  VisitReportTotals,
  Webhook,
  WebhookDelivery,
} from './admin';
export {
  adminMockFailure,
  createAdminMockClient,
  filterAuditEvents,
  filterStaffUsers,
  filterVisitRows,
  MOCK_API_KEYS,
  MOCK_API_SCOPES,
  MOCK_AUDIT_EVENTS,
  MOCK_DASHBOARD,
  MOCK_FACILITIES,
  MOCK_FIELD_TYPES,
  MOCK_FORM_DEFINITIONS,
  MOCK_INTEGRATIONS,
  MOCK_PERMISSIONS,
  MOCK_SMART_APPS,
  MOCK_STAFF_USERS,
  MOCK_VISIT_ROWS,
  MOCK_WEBHOOKS,
  STAFF_ROLE_LABELS,
  totalsFor,
} from './mock/admin';
export type { AdminMockOptions } from './mock/admin';

/* Orders, results and the typed inbox. Fixture-backed for the same reason: the
   aggregates answer NotImplemented in `apps/api` today, and the client shape is
   the one an HTTP client will satisfy. */
export {
  ASSIGNMENTS,
  createWorklistClient,
  filterInbox,
  filterOrders,
  filterResults,
  INBOX_STREAMS,
  isBulkSignable,
  ORDER_CATEGORIES,
  ORDER_PRIORITIES,
  ORDER_STATUSES,
  patientProblems,
  rankCatalog,
  RESULT_FLAGS,
  RESULT_STATUSES,
  slaState,
  useInbox,
  useOrders,
  useResults,
  WARNING_TIERS,
  warningsFor,
  worklist,
} from './worklist';
export type {
  Assignment,
  InboxItem,
  InboxListQuery,
  InboxStream,
  Order,
  OrderCatalogEntry,
  OrderCategory,
  OrderListQuery,
  OrderPriority,
  OrderStatus,
  OrderWarning,
  PatientProblem,
  PriorValue,
  ResultAnalyte,
  ResultFlag,
  ResultListQuery,
  ResultReport,
  ResultStatus,
  SlaState,
  WarningTier,
  WorklistClient,
  WorklistData,
  WorklistHookOptions,
} from './worklist';
export {
  MOCK_INBOX_ITEMS,
  MOCK_ORDER_CATALOG,
  MOCK_ORDER_DESTINATIONS,
  MOCK_ORDER_WARNINGS,
  MOCK_ORDERS,
  MOCK_PATIENT_PROBLEMS,
  MOCK_RESULTS,
  mockResultById,
} from './mock/fixtures';

/* Billing and the revenue cycle. Fixture-backed for the same reason as the two
   blocks above: `apps/api` reserves claims and payments and answers 501, and
   the other three aggregates have no segment yet. */
export {
  AGEING_BUCKETS,
  billing,
  CLAIM_STATUSES,
  createBillingClient,
  DUNNING_STAGES,
  FEE_SHEET_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  REMITTANCE_LINE_STATES,
  REMITTANCE_STATUSES,
  useClaims,
  useFeeSheets,
  usePayments,
  useRemittances,
  useStatements,
} from './billing';
export type {
  AgeingBucket,
  BillingClient,
  BillingData,
  BillingHookOptions,
  BillingPatientRef,
  ChargeDiagnosis,
  ChargeLine,
  Claim,
  ClaimEvent,
  ClaimListQuery,
  ClaimScrubError,
  ClaimServiceLine,
  ClaimStatus,
  DunningStage,
  FeeSheet,
  FeeSheetListQuery,
  FeeSheetStatus,
  PayerRef,
  Payment,
  PaymentAllocation,
  PaymentListQuery,
  PaymentMethodKind,
  PaymentMethodRef,
  PaymentPlan,
  PaymentStatus,
  ProcedureCode,
  Remittance,
  RemittanceLine,
  RemittanceLineState,
  RemittanceListQuery,
  RemittanceStatus,
  StatementAccount,
  StatementLine,
  StatementListQuery,
} from './billing';
export {
  filterClaims,
  filterFeeSheets,
  filterPayments,
  filterRemittances,
  filterStatements,
  MOCK_CLAIMS,
  MOCK_FEE_SHEETS,
  MOCK_PAYERS,
  MOCK_PAYMENTS,
  MOCK_PROCEDURE_CATALOG,
  MOCK_PROCEDURE_PANELS,
  MOCK_REMITTANCES,
  MOCK_STATEMENT_ACCOUNTS,
} from './mock/billing';
