#!/usr/bin/env node
/**
 * THE BROWSER'S COPY OF THE ROLE TABLE IS GENERATED FROM THE API'S.
 *
 * `apps/web/src/lib/api/capabilities.ts` exists because the demonstration build
 * has no API to ask - `NEXT_PUBLIC_API_MODE=mock` is the documented default -
 * so the mock client answers `/bff/v0/me` from a table instead. A table the
 * browser holds and nothing checks is how a client and a server come to hold
 * different beliefs about the same permission, and the divergence is silent:
 * both sides keep working and they disagree about who may sign an order.
 *
 * So the table is not maintained, it is EMITTED, and this script is both halves:
 *
 *   node scripts/ci/capability-parity.mjs           regenerate and diff, exit 1 on drift
 *   node scripts/ci/capability-parity.mjs --write   emit it
 *
 * Same shape as `roadmap:check`, which is the local idiom for a committed file
 * derived from source. It matters more than it looks: the first version of this
 * mirror was WRITTEN by hand, by an author holding this exact hazard in mind,
 * and was wrong in eight ways across four roles. Generation removes the step
 * that failed rather than asking for more care at it.
 *
 * ## The parser does not go away, and it should be said plainly
 *
 * This reads `apps/api/src/policy/permissions.ts` as text rather than importing
 * it: the module is TypeScript, there is no root `tsx`, and `apps/api/dist` does
 * not exist when `verify` reaches this point - `build` is the last link in that
 * chain. `scripts/roadmap/build.mjs` has the same constraint and answers it the
 * same way (`keysIn`, a regex over the catalogue sources). So generation buys
 * an unmaintainable-by-hand artefact, not a parser-free one, and the parser
 * keeps its own tests - including the one for `admin: PERMISSIONS`, a form a
 * bracket-only reader turns into an empty set that then AGREES with an empty
 * browser entry.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const API_SOURCE = 'apps/api/src/policy/permissions.ts';
const WEB_SOURCE = 'apps/web/src/lib/api/capabilities.ts';

/** Everything above the table in the emitted file. */
const HEADER = `/**
 * What each role may do, mirrored from the API.
 *
 * GENERATED by \`scripts/ci/capability-parity.mjs\` from
 * \`apps/api/src/policy/permissions.ts\`. Do not edit: run \`pnpm capabilities\`.
 *
 * The staff application asks \`/bff/v0/me\` for this and uses the answer to stop
 * offering an action the server will refuse (#313). In the demonstration build
 * there is no server to ask - \`NEXT_PUBLIC_API_MODE=mock\` is the documented
 * default - so the mock client answers from this table, and the demonstration
 * then behaves the way a deployment does rather than offering a biller "Sign
 * orders".
 *
 * Nothing here is a security boundary. Every route enforces its own permission;
 * this only decides what the interface offers.
 */
`;

/** Everything below it. Hand-written once, emitted verbatim thereafter. */
const FOOTER = `
/**
 * The permissions a principal holding \`roles\` has, as the API would resolve
 * them.
 *
 * A role this table does not know contributes nothing rather than throwing,
 * which is the API's own rule: a deployment that renames a role should lose
 * access, not break the interface.
 */
export function capabilitiesForRoles(roles: readonly string[]): string[] {
  const held = new Set<string>();
  for (const role of roles) {
    for (const capability of ROLE_CAPABILITIES[role] ?? []) held.add(capability);
  }
  return [...held].sort();
}
`;

/** Every identifier inside the first array literal after `marker`. */
function arrayAfter(source, marker) {
  const start = source.indexOf(marker);
  if (start === -1) return null;
  const open = source.indexOf('[', start);
  if (open === -1) return null;
  let depth = 0;
  for (let index = open; index < source.length; index += 1) {
    if (source[index] === '[') depth += 1;
    else if (source[index] === ']') {
      depth -= 1;
      if (depth === 0) return source.slice(open, index + 1);
    }
  }
  return null;
}

/** `{ role: Set<permission> }` from a `ROLE_PERMISSIONS`-shaped object literal. */
function parseRoleTable(source, marker, expandAll) {
  const start = source.indexOf(marker);
  if (start === -1) throw new Error(`${marker} not found`);
  const open = source.indexOf('{', start);
  let depth = 0;
  let end = -1;
  for (let index = open; index < source.length; index += 1) {
    if (source[index] === '{') depth += 1;
    else if (source[index] === '}') {
      depth -= 1;
      if (depth === 0) {
        end = index;
        break;
      }
    }
  }
  const body = source.slice(open + 1, end);

  const table = new Map();
  const roleHead = /(?:^|\n)\s{2}('?[a-zA-Z][a-zA-Z-]*'?)\s*:\s*(PERMISSIONS|\[)/g;
  let match;
  while ((match = roleHead.exec(body)) !== null) {
    const role = match[1].replaceAll("'", '');
    if (match[2] === 'PERMISSIONS') {
      table.set(role, new Set(expandAll));
      continue;
    }
    const arrayStart = roleHead.lastIndex - 1;
    let arrayDepth = 0;
    let arrayEnd = -1;
    for (let index = arrayStart; index < body.length; index += 1) {
      if (body[index] === '[') arrayDepth += 1;
      else if (body[index] === ']') {
        arrayDepth -= 1;
        if (arrayDepth === 0) {
          arrayEnd = index;
          break;
        }
      }
    }
    const entries = body.slice(arrayStart, arrayEnd + 1).match(/'[a-zA-Z]+\.[a-zA-Z]+'/g) ?? [];
    table.set(role, new Set(entries.map((entry) => entry.replaceAll("'", ''))));
  }
  return table;
}

export function compare(apiSource, webSource) {
  const permissionsLiteral = arrayAfter(apiSource, 'export const PERMISSIONS');
  if (permissionsLiteral === null) throw new Error('PERMISSIONS literal not found');
  const all = (permissionsLiteral.match(/'[a-zA-Z]+\.[a-zA-Z]+'/g) ?? []).map((entry) =>
    entry.replaceAll("'", '')
  );

  const api = parseRoleTable(apiSource, 'export const ROLE_PERMISSIONS', all);
  const web = parseRoleTable(webSource, 'export const ROLE_CAPABILITIES', all);

  const problems = [];
  for (const role of new Set([...api.keys(), ...web.keys()])) {
    const mine = api.get(role);
    const theirs = web.get(role);
    if (mine === undefined) {
      problems.push(`${role}: the browser knows a role the API does not`);
      continue;
    }
    if (theirs === undefined) {
      problems.push(`${role}: the API knows a role the browser does not`);
      continue;
    }
    const missing = [...mine].filter((permission) => !theirs.has(permission)).sort();
    const extra = [...theirs].filter((permission) => !mine.has(permission)).sort();
    if (missing.length > 0) problems.push(`${role}: the browser is missing ${missing.join(', ')}`);
    if (extra.length > 0) problems.push(`${role}: the browser claims ${extra.join(', ')}`);
  }
  return { problems, roles: api.size };
}

/** The browser table, exactly as it is committed. */
export async function render(apiSource) {
  const permissionsLiteral = arrayAfter(apiSource, 'export const PERMISSIONS');
  if (permissionsLiteral === null) throw new Error('PERMISSIONS literal not found');
  const all = (permissionsLiteral.match(/'[a-zA-Z]+\.[a-zA-Z]+'/g) ?? []).map((entry) =>
    entry.replaceAll("'", '')
  );
  const api = parseRoleTable(apiSource, 'export const ROLE_PERMISSIONS', all);

  const entries = [...api.entries()]
    .map(([role, permissions]) => {
      const key = /^[a-zA-Z]+$/.test(role) ? role : `'${role}'`;
      const items = [...permissions].map((permission) => `    '${permission}',\n`).join('');
      return `  ${key}: [\n${items}  ],\n`;
    })
    .join('');

  const source = `${HEADER}export const ROLE_CAPABILITIES: Readonly<Record<string, readonly string[]>> = {\n${entries}};\n${FOOTER}`;

  /* Formatted here rather than left to a contributor, because `format:check`
     runs in the same `verify` chain: an emitter that produces a file the
     formatter rejects turns one gate green by making another red. The roadmap
     generator loads prettier for the same reason. */
  const { default: prettier } = await import('prettier');
  const config = (await prettier.resolveConfig(WEB_SOURCE)) ?? {};
  return await prettier.format(source, { ...config, filepath: WEB_SOURCE });
}

async function main() {
  const apiSource = readFileSync(API_SOURCE, 'utf8');
  const expected = await render(apiSource);

  if (process.argv.includes('--write')) {
    writeFileSync(WEB_SOURCE, expected);
    process.stdout.write(`capability-parity: wrote ${WEB_SOURCE}.\n`);
    return 0;
  }

  const actual = existsSync(WEB_SOURCE) ? readFileSync(WEB_SOURCE, 'utf8') : '';
  if (actual === expected) {
    const { roles } = compare(apiSource, actual);
    process.stdout.write(
      `capability-parity: ${roles} roles agree between the API and the browser.\n`
    );
    return 0;
  }

  /* The text comparison is what decides, because it catches a difference the
     per-role one cannot see - ordering, a stray edit, a lost comment. The
     per-role report is then run for the message, so the failure names the roles
     and the identifiers rather than telling somebody a file differs. */
  const { problems } = compare(apiSource, actual);
  process.stderr.write(
    `capability-parity: ${WEB_SOURCE} is not what the API's table generates.\n` +
      (problems.length > 0
        ? problems.map((problem) => `  ${problem}\n`).join('')
        : '  the permissions agree; the file differs in ordering, comments or formatting\n') +
      `\nRun \`pnpm capabilities\` and commit the result. It is generated, not maintained.\n`
  );
  return 1;
}

if (process.argv[1] && import.meta.filename === process.argv[1]) {
  process.exit(await main());
}
