#!/usr/bin/env node
/**
 * THE BROWSER'S COPY OF THE ROLE TABLE IS GENERATED FROM THE API'S.
 *
 * `apps/web/src/lib/api/capabilities.ts` exists because the demonstration build
 * has no API to ask - `NEXT_PUBLIC_API_MODE=mock` is the documented default -
 * so the mock client answers `/bff/v0/me` from a table instead. A table the
 * browser holds and nothing checks is how a client and a server come to hold
 * different beliefs about the same permission, and the divergence is silent:
 * both sides keep working and they disagree about who may sign an order.
 *
 * So the table is not maintained, it is EMITTED, and this script is both halves:
 *
 *   node --experimental-strip-types scripts/ci/capability-parity.mjs
 *   node --experimental-strip-types scripts/ci/capability-parity.mjs --write
 *
 * Same shape as `roadmap:check`, which is the local idiom for a committed file
 * derived from source. It matters more than it looks: the first version of this
 * mirror was WRITTEN by hand, by an author holding this exact hazard in mind,
 * and was wrong in eight ways across four roles. Generation removes the step
 * that failed rather than asking for more care at it.
 *
 * ## Why this imports rather than reads
 *
 * The first version of this script parsed `permissions.ts` as text, because
 * `apps/api/dist` does not exist when `verify` reaches this point - `build` is
 * the last link in that chain - and `scripts/roadmap/build.mjs` answers the
 * same constraint the same way. It handled the two forms it had seen, an array
 * literal and the bare `PERMISSIONS` identifier, and SKIPPED anything else.
 *
 * `read-only: READ_EVERYTHING` is anything else. It is a computed bundle -
 * every `.read` permission minus the supervisory ones - and the parser dropped
 * the role silently, so the browser told a read-only account it could do
 * nothing at all. Regenerate-and-diff could not catch it: both sides of that
 * comparison come from this file, so a generator that omits a role omits it
 * from the expectation too and the two agree. A derived artefact cannot be its
 * own control.
 *
 * A regex cannot evaluate `PERMISSIONS.filter(...)`, and the next bundle will
 * be some third form. So this imports the module and asks it, which is exact by
 * construction and has no form to fail to recognise. Node strips the types;
 * the flag is a no-op from 22.18 and is passed for the rest of the supported
 * `^22.12` range. Nothing is built first - the SOURCE is imported, which also
 * removes the chance of checking against a stale `dist`.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const API_SOURCE = 'apps/api/src/policy/permissions.ts';
const WEB_SOURCE = 'apps/web/src/lib/api/capabilities.ts';

/** Everything above the table in the emitted file. */
const HEADER = `/**
 * What each role may do, mirrored from the API.
 *
 * GENERATED by \`scripts/ci/capability-parity.mjs\` from
 * \`apps/api/src/policy/permissions.ts\`. Do not edit: run \`pnpm capabilities\`.
 *
 * The staff application asks \`/bff/v0/me\` for this and uses the answer to stop
 * offering an action the server will refuse (#313). In the demonstration build
 * there is no server to ask - \`NEXT_PUBLIC_API_MODE=mock\` is the documented
 * default - so the mock client answers from this table, and the demonstration
 * then behaves the way a deployment does rather than offering a biller "Sign
 * orders".
 *
 * Nothing here is a security boundary. Every route enforces its own permission;
 * this only decides what the interface offers.
 */
`;

/** Everything below it. Hand-written once, emitted verbatim thereafter. */
const FOOTER = `
/**
 * The permissions a principal holding \`roles\` has, as the API would resolve
 * them.
 *
 * A role this table does not know contributes nothing rather than throwing,
 * which is the API's own rule: a deployment that renames a role should lose
 * access, not break the interface.
 */
export function capabilitiesForRoles(roles: readonly string[]): string[] {
  const held = new Set<string>();
  for (const role of roles) {
    for (const capability of ROLE_CAPABILITIES[role] ?? []) held.add(capability);
  }
  return [...held].sort();
}
`;

/**
 * `{ role: Set<permission> }` from a module's exported role table.
 *
 * Throws rather than returning an empty table when the export is missing: an
 * empty table agrees with an empty browser file, so a silent failure here would
 * report parity instead of the absence of both halves.
 */
export async function readRoleTable(path, exportName) {
  const module = await import(pathToFileURL(path).href);
  const table = module[exportName];
  if (table === undefined || table === null || typeof table !== 'object') {
    throw new Error(`${path} does not export ${exportName}`);
  }
  const entries = Object.entries(table);
  if (entries.length === 0) throw new Error(`${path} exports an empty ${exportName}`);
  return new Map(entries.map(([role, permissions]) => [role, new Set(permissions)]));
}

/** Per-role differences, for the failure message rather than for the verdict. */
export function compare(api, web) {
  const problems = [];
  for (const role of new Set([...api.keys(), ...web.keys()])) {
    const mine = api.get(role);
    const theirs = web.get(role);
    if (mine === undefined) {
      problems.push(`${role}: the browser knows a role the API does not`);
      continue;
    }
    if (theirs === undefined) {
      problems.push(`${role}: the API knows a role the browser does not`);
      continue;
    }
    const missing = [...mine].filter((permission) => !theirs.has(permission)).sort();
    const extra = [...theirs].filter((permission) => !mine.has(permission)).sort();
    if (missing.length > 0) problems.push(`${role}: the browser is missing ${missing.join(', ')}`);
    if (extra.length > 0) problems.push(`${role}: the browser claims ${extra.join(', ')}`);
  }
  return { problems, roles: api.size };
}

/**
 * The browser table before formatting.
 *
 * Separate from `render` so this file's own tests can exercise the emitter
 * without loading prettier: the `CI scripts (node --test)` job runs with
 * `install: false`, on the stated ground that everything under `scripts/ci` is
 * dependency-free, and a test that imported prettier turned that job red while
 * `pnpm verify` stayed green locally.
 */
export function renderSource(api) {
  const entries = [...api.entries()]
    .map(([role, permissions]) => {
      const key = /^[a-zA-Z][a-zA-Z0-9]*$/.test(role) ? role : `'${role}'`;
      const items = [...permissions].map((permission) => `    '${permission}',\n`).join('');
      return `  ${key}: [\n${items}  ],\n`;
    })
    .join('');

  return `${HEADER}export const ROLE_CAPABILITIES: Readonly<Record<string, readonly string[]>> = {\n${entries}};\n${FOOTER}`;
}

/**
 * The browser table, exactly as it is committed.
 *
 * Formatted here rather than left to a contributor, because `format:check` runs
 * in the same `verify` chain: an emitter that produces a file the formatter
 * rejects turns one gate green by making another red. The roadmap generator
 * loads prettier for the same reason.
 */
export async function render(api) {
  const { default: prettier } = await import('prettier');
  const config = (await prettier.resolveConfig(WEB_SOURCE)) ?? {};
  return await prettier.format(renderSource(api), { ...config, filepath: WEB_SOURCE });
}

async function main() {
  const api = await readRoleTable(API_SOURCE, 'ROLE_PERMISSIONS');
  const expected = await render(api);

  if (process.argv.includes('--write')) {
    writeFileSync(WEB_SOURCE, expected);
    process.stdout.write(`capability-parity: wrote ${WEB_SOURCE}.\n`);
    return 0;
  }

  const actual = existsSync(WEB_SOURCE) ? await readFile(WEB_SOURCE, 'utf8') : '';
  if (actual === expected) {
    /* Counted on the BROWSER's table, not the API's. A mutation that made the
       generator drop a role printed `8 roles agree` from `api.size` while the
       emitted file held seven - a success message describing the wrong side of
       the comparison it was reporting on. */
    const web = await readRoleTable(WEB_SOURCE, 'ROLE_CAPABILITIES');
    process.stdout.write(
      `capability-parity: ${web.size} roles in the browser table agree with the API.\n`
    );
    return 0;
  }

  /* The text comparison is what decides, because it catches a difference the
     per-role one cannot see - ordering, a stray edit, a lost comment. The
     per-role report is then run for the message, so the failure names the roles
     and the identifiers rather than telling somebody a file differs. A browser
     file too broken to import still fails, with the import error as the
     reason. */
  let problems;
  try {
    problems = compare(api, await readRoleTable(WEB_SOURCE, 'ROLE_CAPABILITIES')).problems;
  } catch (error) {
    problems = [`${WEB_SOURCE} could not be read: ${error.message}`];
  }
  process.stderr.write(
    `capability-parity: ${WEB_SOURCE} is not what the API's table generates.\n` +
      (problems.length > 0
        ? problems.map((problem) => `  ${problem}\n`).join('')
        : '  the permissions agree; the file differs in ordering, comments or formatting\n') +
      `\nRun \`pnpm capabilities\` and commit the result. It is generated, not maintained.\n`
  );
  return 1;
}

if (process.argv[1] && import.meta.filename === process.argv[1]) {
  process.exit(await main());
}
