import type { Measure, Sex } from '../index.js';

/**
 * GENERATED from the CDC growth-chart files, by the snippet in the pull request
 * that introduced this package.
 *
 * These are the CDC's OWN published percentile values - not this package's
 * output recorded as a snapshot. That distinction is the whole point: a snapshot
 * test proves the code still does what it did, and this proves it does what the
 * CDC says. A sample rather than all fifteen thousand, spread across both sexes
 * and each table's ends and middle, because the generator already checks every
 * one at build time and this is the copy that travels with the tests.
 */
export interface PublishedPercentile {
  readonly measure: Measure;
  /** Which side of the 24-month seam this row is from. */
  readonly infant: boolean;
  readonly sex: Sex;
  /** Age in months, or length in centimetres for weight-for-length. */
  readonly index: number;
  readonly percentile: number;
  readonly value: number;
}

export const PUBLISHED_PERCENTILES: readonly PublishedPercentile[] = [
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 5,
    value: 2.52690402,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 50,
    value: 3.530203168,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 95,
    value: 4.34029274,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 18.5,
    percentile: 5,
    value: 9.901830339,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 18.5,
    percentile: 50,
    value: 11.80477902,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 18.5,
    percentile: 95,
    value: 14.14187481,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 36,
    percentile: 5,
    value: 12.03991048,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 36,
    percentile: 50,
    value: 14.32994444,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'male',
    index: 36,
    percentile: 95,
    value: 17.40816491,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 5,
    value: 2.54790518,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 50,
    value: 3.39918645,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 95,
    value: 4.152636594,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 18.5,
    percentile: 5,
    value: 9.394782429,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 18.5,
    percentile: 50,
    value: 11.08868151,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 18.5,
    percentile: 95,
    value: 13.28904061,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 36,
    percentile: 5,
    value: 11.59928903,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 36,
    percentile: 50,
    value: 13.86507382,
  },
  {
    measure: 'weight-for-age',
    infant: true,
    sex: 'female',
    index: 36,
    percentile: 95,
    value: 17.24468787,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 5,
    value: 45.5684091,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 50,
    value: 49.98888408,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 95,
    value: 54.30721197,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 17.5,
    percentile: 5,
    value: 76.3374214,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 17.5,
    percentile: 50,
    value: 81.44383603,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 17.5,
    percentile: 95,
    value: 86.88645473,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 35.5,
    percentile: 5,
    value: 89.33241837,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 35.5,
    percentile: 50,
    value: 95.44636981,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'male',
    index: 35.5,
    percentile: 95,
    value: 102.1174472,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 5,
    value: 45.5756074,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 50,
    value: 49.28639612,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 95,
    value: 53.77290878,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 17.5,
    percentile: 5,
    value: 74.51183666,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 17.5,
    percentile: 50,
    value: 79.81491852,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 17.5,
    percentile: 95,
    value: 84.99774469,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 35.5,
    percentile: 5,
    value: 88.00936554,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 35.5,
    percentile: 50,
    value: 94.43382278,
  },
  {
    measure: 'length-for-age',
    infant: true,
    sex: 'female',
    index: 35.5,
    percentile: 95,
    value: 101.0475227,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 5,
    value: 32.14881105,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 50,
    value: 35.81366835,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 0,
    percentile: 95,
    value: 38.51574,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 18.5,
    percentile: 5,
    value: 45.67997038,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 18.5,
    percentile: 50,
    value: 47.85820606,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 18.5,
    percentile: 95,
    value: 50.07918514,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 36,
    percentile: 5,
    value: 46.86520671,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 36,
    percentile: 50,
    value: 49.68393611,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'male',
    index: 36,
    percentile: 95,
    value: 52.22627901,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 5,
    value: 32.25089861,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 50,
    value: 34.7115617,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 0,
    percentile: 95,
    value: 37.65137722,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 18.5,
    percentile: 5,
    value: 44.4155332,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 18.5,
    percentile: 50,
    value: 46.60950084,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 18.5,
    percentile: 95,
    value: 48.79525631,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 36,
    percentile: 5,
    value: 45.98061022,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 36,
    percentile: 50,
    value: 48.63342328,
  },
  {
    measure: 'head-circumference-for-age',
    infant: true,
    sex: 'female',
    index: 36,
    percentile: 95,
    value: 51.1038697,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 45,
    percentile: 5,
    value: 1.690593749,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 45,
    percentile: 50,
    value: 2.289757735,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 45,
    percentile: 95,
    value: 2.824861387,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 74.5,
    percentile: 5,
    value: 8.434590571,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 74.5,
    percentile: 50,
    value: 9.507773605,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 74.5,
    percentile: 95,
    value: 10.92354547,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 103.5,
    percentile: 5,
    value: 14.62739094,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 103.5,
    percentile: 50,
    value: 16.43469418,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'male',
    index: 103.5,
    percentile: 95,
    value: 19.09143177,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 45,
    percentile: 5,
    value: 1.69530853,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 45,
    percentile: 50,
    value: 2.305396985,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 45,
    percentile: 95,
    value: 2.974943903,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 74.5,
    percentile: 5,
    value: 8.213087629,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 74.5,
    percentile: 50,
    value: 9.337865054,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 74.5,
    percentile: 95,
    value: 10.84904795,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 103.5,
    percentile: 5,
    value: 14.33902847,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 103.5,
    percentile: 50,
    value: 16.19103966,
  },
  {
    measure: 'weight-for-length',
    infant: true,
    sex: 'female',
    index: 103.5,
    percentile: 95,
    value: 19.43416015,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 5,
    value: 10.64009004,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 50,
    value: 12.6707633,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 95,
    value: 15.18777349,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 5,
    value: 27.50030694,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 50,
    value: 36.07262569,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 95,
    value: 52.55602363,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 240,
    percentile: 5,
    value: 55.66071006,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 240,
    percentile: 50,
    value: 70.59761453,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'male',
    index: 240,
    percentile: 95,
    value: 95.71431427,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 5,
    value: 10.2102741,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 50,
    value: 12.05503983,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 95,
    value: 14.56636479,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 5,
    value: 27.83564104,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 50,
    value: 37.39088668,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 95,
    value: 54.95703466,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 240,
    percentile: 5,
    value: 46.28963394,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 240,
    percentile: 50,
    value: 58.21897289,
  },
  {
    measure: 'weight-for-age',
    infant: false,
    sex: 'female',
    index: 240,
    percentile: 95,
    value: 82.95375457,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 5,
    value: 80.72977321,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 50,
    value: 86.45220101,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 95,
    value: 92.19687928,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 5,
    value: 132.3990267,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 50,
    value: 143.7303663,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 95,
    value: 155.5385858,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 240,
    percentile: 5,
    value: 165.0388523,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 240,
    percentile: 50,
    value: 176.8492322,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'male',
    index: 240,
    percentile: 95,
    value: 188.5290125,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 5,
    value: 79.25981989,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 50,
    value: 84.97555512,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 95,
    value: 90.66354871,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 5,
    value: 132.4013028,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 50,
    value: 144.2609497,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 95,
    value: 156.3754566,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 240,
    percentile: 5,
    value: 152.6507234,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 240,
    percentile: 50,
    value: 163.338251,
  },
  {
    measure: 'stature-for-age',
    infant: false,
    sex: 'female',
    index: 240,
    percentile: 95,
    value: 173.9506901,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 5,
    value: 14.73731947,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 50,
    value: 16.57502768,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 24,
    percentile: 95,
    value: 19.33801062,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 5,
    value: 14.56000917,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 50,
    value: 17.20088732,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 132.5,
    percentile: 95,
    value: 23.21358351,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 240.5,
    percentile: 5,
    value: 19.13539969,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 240.5,
    percentile: 50,
    value: 23.04137734,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'male',
    index: 240.5,
    percentile: 95,
    value: 30.63106054,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 5,
    value: 14.39787089,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 50,
    value: 16.42339664,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 24,
    percentile: 95,
    value: 19.10623522,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 5,
    value: 14.40290497,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 50,
    value: 17.46906585,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 132.5,
    percentile: 95,
    value: 24.14141407,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 240.5,
    percentile: 5,
    value: 17.81856356,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 240.5,
    percentile: 50,
    value: 21.72190973,
  },
  {
    measure: 'bmi-for-age',
    infant: false,
    sex: 'female',
    index: 240.5,
    percentile: 95,
    value: 31.79902964,
  },
];
