import { describe, expect, it } from 'vitest';

import * as api from './index.js';
import {
  ANSWERABLE_FIELD_TYPES,
  CONDITION_EFFECTS,
  CONDITION_OPERATORS,
  DEFAULT_QUESTIONNAIRE_BASE_URL,
  FIELD_TYPES,
  FORM_BINDINGS,
  FORM_STATUSES,
  FORM_SUBMISSION_STATUSES,
  PRESENTATION_FIELD_TYPES,
  PROMOTED_FIELD_TYPES,
  RENDER_GRID_COLUMNS,
  UCUM_SYSTEM,
  assertPublishable,
  compileDefinition,
  definitionContentHash,
  evaluateConditions,
  fieldStateFor,
  fromQuestionnaireResponse,
  isAnswerableFieldType,
  isPromoted,
  promote,
  promotedFieldTypeFor,
  publishDefinition,
  toPromotionManifest,
  toQuestionnaireResponse,
  validateResponse,
} from './index.js';
import type {
  AnswerableField,
  AnswerableFieldType,
  BooleanField,
  CodedAnswer,
  CodedValueField,
  CompileOptions,
  CompiledCondition,
  CompiledField,
  CompiledForm,
  ConditionEffect,
  ConditionLeaf,
  ConditionNode,
  ConditionOperator,
  ConditionScalar,
  DateField,
  DateTimeField,
  DensityHint,
  FhirAttachment,
  FhirCoding,
  FhirQuantity,
  FieldLayout,
  FieldState,
  FieldStateMap,
  FieldType,
  FileReferenceField,
  FormBinding,
  FormCompileError,
  FormConditionRule,
  FormDefinition,
  FormField,
  FormPromotionError,
  FormStatus,
  FormSubmissionStatus,
  FormSubmissionView,
  FormValidationError,
  FormValues,
  FormValuesSchema,
  LongTextField,
  MultiSelectField,
  NumberField,
  PresentationField,
  PresentationFieldType,
  PrintBlock,
  PrintHeadingBlock,
  PrintLayout,
  PrintPageBreakBlock,
  PrintParagraphBlock,
  PrintRepeatTableBlock,
  PrintSignatureBlock,
  PrintTableColumn,
  PrintValueSlotBlock,
  PrintValueStyle,
  PromotedFieldSpec,
  PromotedFieldType,
  PromotedValue,
  PromotionFlags,
  PromotionManifest,
  PublishedFormDefinition,
  PublishedVersionRecord,
  Questionnaire,
  QuestionnaireAnswerOption,
  QuestionnaireEnableOperator,
  QuestionnaireEnableWhen,
  QuestionnaireGap,
  QuestionnaireItem,
  QuestionnaireItemType,
  QuestionnaireResponse,
  QuestionnaireResponseAnswer,
  QuestionnaireResponseItem,
  QuestionnaireResponseStatus,
  QuestionnaireStatus,
  RenderFieldNode,
  RenderGroupNode,
  RenderLayout,
  RenderNode,
  RenderTree,
  RepeatingGroupField,
  ScaleField,
  SectionHeaderField,
  SelectOption,
  ShortTextField,
  SignatureField,
  SingleSelectField,
  StaticTextField,
  ValidatedResponse,
} from './index.js';

/**
 * The exact runtime surface. Adding an export without adding it here fails the
 * build on purpose: a package that four apps compile against cannot grow an
 * accidental public function, because removing one afterwards is a breaking
 * change to somebody.
 */
const EXPECTED_EXPORTS = [
  'ANSWERABLE_FIELD_TYPES',
  'CONDITION_EFFECTS',
  'CONDITION_OPERATORS',
  'DEFAULT_QUESTIONNAIRE_BASE_URL',
  'FIELD_TYPES',
  'FORM_BINDINGS',
  'FORM_STATUSES',
  'FORM_SUBMISSION_STATUSES',
  'PRESENTATION_FIELD_TYPES',
  'PROMOTED_FIELD_TYPES',
  'RENDER_GRID_COLUMNS',
  'UCUM_SYSTEM',
  'assertPublishable',
  'compileDefinition',
  'definitionContentHash',
  'evaluateConditions',
  'fieldStateFor',
  'fromQuestionnaireResponse',
  'isAnswerableFieldType',
  'isPromoted',
  'promote',
  'promotedFieldTypeFor',
  'publishDefinition',
  'toPromotionManifest',
  'toQuestionnaireResponse',
  'validateResponse',
] as const;

describe('public API surface', () => {
  it('exports exactly the documented set of runtime names', () => {
    expect(Object.keys(api).sort()).toStrictEqual([...EXPECTED_EXPORTS].sort());
  });

  it('exports every name the rest of the product imports by name', () => {
    const bound = [
      ANSWERABLE_FIELD_TYPES,
      CONDITION_EFFECTS,
      CONDITION_OPERATORS,
      DEFAULT_QUESTIONNAIRE_BASE_URL,
      FIELD_TYPES,
      FORM_BINDINGS,
      FORM_STATUSES,
      FORM_SUBMISSION_STATUSES,
      PRESENTATION_FIELD_TYPES,
      PROMOTED_FIELD_TYPES,
      RENDER_GRID_COLUMNS,
      UCUM_SYSTEM,
      assertPublishable,
      compileDefinition,
      definitionContentHash,
      evaluateConditions,
      fieldStateFor,
      fromQuestionnaireResponse,
      isAnswerableFieldType,
      isPromoted,
      promote,
      promotedFieldTypeFor,
      publishDefinition,
      toPromotionManifest,
      toQuestionnaireResponse,
      validateResponse,
    ];
    expect(bound).toHaveLength(EXPECTED_EXPORTS.length);
    expect(bound.every((value) => value !== undefined)).toBe(true);
  });
});

describe('catalogue constants', () => {
  it('lists fifteen field types, twelve of which carry an answer', () => {
    expect(FIELD_TYPES).toHaveLength(15);
    expect(ANSWERABLE_FIELD_TYPES).toHaveLength(12);
    expect(PRESENTATION_FIELD_TYPES).toStrictEqual(['sectionHeader', 'staticText']);
    expect(FIELD_TYPES).toContain('repeatingGroup');
  });

  it('agrees with its own guard about which types carry an answer', () => {
    for (const type of FIELD_TYPES) {
      expect(isAnswerableFieldType(type)).toBe(
        (ANSWERABLE_FIELD_TYPES as readonly string[]).includes(type)
      );
    }
  });

  it('lists ten leaf operators and four effects', () => {
    expect(CONDITION_OPERATORS).toHaveLength(10);
    expect(CONDITION_EFFECTS).toStrictEqual(['show', 'hide', 'require', 'optional']);
  });

  it('mirrors the database enums it has to agree with', () => {
    expect(FORM_BINDINGS).toStrictEqual(['PATIENT', 'ENCOUNTER', 'PORTAL', 'REFERRAL']);
    expect(FORM_STATUSES).toStrictEqual(['DRAFT', 'PUBLISHED', 'RETIRED']);
    expect(FORM_SUBMISSION_STATUSES).toStrictEqual([
      'IN_PROGRESS',
      'COMPLETED',
      'SIGNED',
      'AMENDED',
      'ENTERED_IN_ERROR',
    ]);
    expect(PROMOTED_FIELD_TYPES).toStrictEqual([
      'text',
      'number',
      'date',
      'boolean',
      'code',
      'quantity',
    ]);
  });
});

describe('exported types', () => {
  it('names every type the public functions mention', () => {
    // Compiling this file at all is the assertion: each of these is imported as
    // a type above, so a removed or renamed type export fails type-check.
    const names: readonly string[] = [
      'AnswerableField',
      'AnswerableFieldType',
      'BooleanField',
      'CodedAnswer',
      'CodedValueField',
      'CompileOptions',
      'CompiledCondition',
      'CompiledField',
      'CompiledForm',
      'ConditionEffect',
      'ConditionLeaf',
      'ConditionNode',
      'ConditionOperator',
      'ConditionScalar',
      'DateField',
      'DateTimeField',
      'DensityHint',
      'FhirAttachment',
      'FhirCoding',
      'FhirQuantity',
      'FieldLayout',
      'FieldState',
      'FieldStateMap',
      'FieldType',
      'FileReferenceField',
      'FormBinding',
      'FormCompileError',
      'FormConditionRule',
      'FormDefinition',
      'FormField',
      'FormPromotionError',
      'FormStatus',
      'FormSubmissionStatus',
      'FormSubmissionView',
      'FormValidationError',
      'FormValues',
      'FormValuesSchema',
      'LongTextField',
      'MultiSelectField',
      'NumberField',
      'PresentationField',
      'PresentationFieldType',
      'PrintBlock',
      'PrintHeadingBlock',
      'PrintLayout',
      'PrintPageBreakBlock',
      'PrintParagraphBlock',
      'PrintRepeatTableBlock',
      'PrintSignatureBlock',
      'PrintTableColumn',
      'PrintValueSlotBlock',
      'PrintValueStyle',
      'PromotedFieldSpec',
      'PromotedFieldType',
      'PromotedValue',
      'PromotionFlags',
      'PromotionManifest',
      'PublishedFormDefinition',
      'PublishedVersionRecord',
      'Questionnaire',
      'QuestionnaireAnswerOption',
      'QuestionnaireEnableOperator',
      'QuestionnaireEnableWhen',
      'QuestionnaireGap',
      'QuestionnaireItem',
      'QuestionnaireItemType',
      'QuestionnaireResponse',
      'QuestionnaireResponseAnswer',
      'QuestionnaireResponseItem',
      'QuestionnaireResponseStatus',
      'QuestionnaireStatus',
      'RenderFieldNode',
      'RenderGroupNode',
      'RenderLayout',
      'RenderNode',
      'RenderTree',
      'RepeatingGroupField',
      'ScaleField',
      'SectionHeaderField',
      'SelectOption',
      'ShortTextField',
      'SignatureField',
      'SingleSelectField',
      'StaticTextField',
      'ValidatedResponse',
    ];
    expect(new Set(names).size).toBe(names.length);
  });
});

/**
 * Type-level anchors: naming each imported type here forces it to be used, so a
 * type export that disappears from `index.ts` fails type-check rather than
 * quietly leaving a consumer with no way to name what a function returns.
 */
export type ApiTypeAnchors = [
  AnswerableField,
  AnswerableFieldType,
  BooleanField,
  CodedAnswer,
  CodedValueField,
  CompileOptions,
  CompiledCondition,
  CompiledField,
  CompiledForm,
  ConditionEffect,
  ConditionLeaf,
  ConditionNode,
  ConditionOperator,
  ConditionScalar,
  DateField,
  DateTimeField,
  DensityHint,
  FhirAttachment,
  FhirCoding,
  FhirQuantity,
  FieldLayout,
  FieldState,
  FieldStateMap,
  FieldType,
  FileReferenceField,
  FormBinding,
  FormCompileError,
  FormConditionRule,
  FormDefinition,
  FormField,
  FormPromotionError,
  FormStatus,
  FormSubmissionStatus,
  FormSubmissionView,
  FormValidationError,
  FormValues,
  FormValuesSchema,
  LongTextField,
  MultiSelectField,
  NumberField,
  PresentationField,
  PresentationFieldType,
  PrintBlock,
  PrintHeadingBlock,
  PrintLayout,
  PrintPageBreakBlock,
  PrintParagraphBlock,
  PrintRepeatTableBlock,
  PrintSignatureBlock,
  PrintTableColumn,
  PrintValueSlotBlock,
  PrintValueStyle,
  PromotedFieldSpec,
  PromotedFieldType,
  PromotedValue,
  PromotionFlags,
  PromotionManifest,
  PublishedFormDefinition,
  PublishedVersionRecord,
  Questionnaire,
  QuestionnaireAnswerOption,
  QuestionnaireEnableOperator,
  QuestionnaireEnableWhen,
  QuestionnaireGap,
  QuestionnaireItem,
  QuestionnaireItemType,
  QuestionnaireResponse,
  QuestionnaireResponseAnswer,
  QuestionnaireResponseItem,
  QuestionnaireResponseStatus,
  QuestionnaireStatus,
  RenderFieldNode,
  RenderGroupNode,
  RenderLayout,
  RenderNode,
  RenderTree,
  RepeatingGroupField,
  ScaleField,
  SectionHeaderField,
  SelectOption,
  ShortTextField,
  SignatureField,
  SingleSelectField,
  StaticTextField,
  ValidatedResponse,
];
